#!/usr/bin/env python3
"""
Build the note_spend RV64IM guest and export its ELF bytes as a Rust constant.

Usage:
    python3 export_rom_rs.py               # build + export
    python3 export_rom_rs.py --skip-build  # export only (assumes already built)
"""

from __future__ import annotations

import hashlib
import json
import os
import subprocess
import sys
from pathlib import Path


def _cargo_home_for_guest(guest_dir: Path) -> Path:
    cargo_home = guest_dir.parent / ".cargo-home-rv64"
    cargo_home.mkdir(parents=True, exist_ok=True)
    _bootstrap_cargo_home(cargo_home)
    config_path = cargo_home / "config.toml"
    if config_path.exists():
        config_path.unlink()
    return cargo_home


def _ensure_symlink(dest: Path, src: Path) -> None:
    if dest.exists() or dest.is_symlink():
        return
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.symlink_to(src, target_is_directory=True)


def _bootstrap_cargo_home(cargo_home: Path) -> None:
    global_cargo = Path.home() / ".cargo"
    _ensure_symlink(cargo_home / "git" / "db", global_cargo / "git" / "db")
    (cargo_home / "git" / "checkouts").mkdir(parents=True, exist_ok=True)
    _ensure_symlink(cargo_home / "registry" / "index", global_cargo / "registry" / "index")
    (cargo_home / "registry" / "cache").mkdir(parents=True, exist_ok=True)
    (cargo_home / "registry" / "src").mkdir(parents=True, exist_ok=True)


def _cargo_offline_args() -> list[str]:
    return ["--offline"] if os.environ.get("NIGHTSTREAM_CARGO_OFFLINE") == "1" else []


def _metadata_for_guest(guest_dir: Path) -> dict:
    cargo_home = _cargo_home_for_guest(guest_dir)
    result = subprocess.run(
        [
            "cargo",
            "metadata",
            *_cargo_offline_args(),
            "--format-version",
            "1",
            "--manifest-path",
            str(guest_dir / "Cargo.toml"),
        ],
        cwd=guest_dir,
        check=True,
        capture_output=True,
        text=True,
        env={**os.environ, "CARGO_HOME": str(cargo_home)},
    )
    return json.loads(result.stdout)


def _nightstream_guest_support(guest_dir: Path) -> tuple[Path, Path]:
    metadata = _metadata_for_guest(guest_dir)
    for package in metadata["packages"]:
        if package["name"] != "nightstream-sdk":
            continue
        manifest_path = Path(package["manifest_path"])
        guest_support_dir = manifest_path.parent / "guest"
        target_json = guest_support_dir / "riscv64im-unknown-none-elf.json"
        linker = guest_support_dir / "riscv64im-unknown-none-elf.ld"
        if target_json.exists() and linker.exists():
            return target_json, linker
    raise RuntimeError("failed to locate nightstream-sdk guest support files via cargo metadata")


def _normalized_target_json(original: Path, target_dir: Path) -> Path:
    target_dir.mkdir(parents=True, exist_ok=True)
    data = json.loads(original.read_text(encoding="utf-8"))
    if not isinstance(data.get("target-pointer-width"), str):
        data["target-pointer-width"] = str(data["target-pointer-width"])
    normalized = target_dir / original.name
    normalized.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")
    return normalized


def _build_rv64im_guest(guest_dir: Path, target_dir: Path) -> Path:
    target_json, linker = _nightstream_guest_support(guest_dir)
    target_json = _normalized_target_json(target_json, target_dir)
    cargo_home = _cargo_home_for_guest(guest_dir)
    rustflags = f"{os.environ.get('RUSTFLAGS', '').strip()} -C link-arg=-T{linker}".strip()
    subprocess.run(
        [
            "cargo",
            "+nightly",
            "build",
            *_cargo_offline_args(),
            "-Z",
            "build-std=core,alloc",
            "-Z",
            "build-std-features=compiler-builtins-mem",
            "--release",
            "--target",
            str(target_json),
        ],
        cwd=guest_dir,
        check=True,
        env={
            **os.environ,
            "CARGO_HOME": str(cargo_home),
            "CARGO_TARGET_DIR": str(target_dir),
            "RUSTFLAGS": rustflags,
        },
    )
    return target_dir / "riscv64im-unknown-none-elf" / "release" / "note_spend"


def _format_rom_module(gen_path: str, elf_bytes: bytes, sha256_hex: str) -> str:
    lines = []
    lines.append(f"// @generated by {gen_path}")
    lines.append(f"// sha256={sha256_hex}")
    lines.append("// format=elf64-rv64im")
    lines.append("")
    lines.append("pub const NOTE_SPEND_ROM_BASE: u64 = 0u64;")
    lines.append(f"pub const NOTE_SPEND_ROM: [u8; {len(elf_bytes)}] = [")
    for i in range(0, len(elf_bytes), 16):
        chunk = elf_bytes[i : i + 16]
        hexes = ", ".join(f"0x{b:02x}" for b in chunk)
        lines.append(f"    {hexes},")
    lines.append("];")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    guest_dir = Path(__file__).resolve().parent
    circuits_dir = guest_dir.parent
    out_rs = circuits_dir / "note_spend_rom.rs"
    target_dir = guest_dir / "target"

    skip_build = "--skip-build" in sys.argv

    if not skip_build:
        print("Building note_spend guest (riscv64im-unknown-none-elf)...")
        elf = _build_rv64im_guest(guest_dir, target_dir)
    else:
        elf = target_dir / "riscv64im-unknown-none-elf" / "release" / "note_spend"

    if not elf.exists():
        raise FileNotFoundError(f"missing expected ELF: {elf}")

    elf_bytes = elf.read_bytes()
    sha256_hex = hashlib.sha256(elf_bytes).hexdigest()

    gen_path = "crates/adapters/nightstream/circuits/note_spend/export_rom_rs.py"
    rs_content = _format_rom_module(gen_path, elf_bytes, sha256_hex)
    out_rs.write_text(rs_content, encoding="utf-8")

    print(f"Wrote {out_rs.name} (elf={len(elf_bytes)}, sha256={sha256_hex})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
