//! Integration tests for Full Viewing Key functionality.
//!
//! These tests demonstrate the complete workflow:
//! 1. Creating notes with FVK encryption
//! 2. Emitting encrypted note events
//! 3. Auditors decrypting and verifying notes
//! 4. Detecting non-truthful ciphertexts

use midnight_privacy::{
    encrypt_note_for_fvk, decrypt_and_verify_note,
    note_commitment, EncryptedNote, FullViewingKey, Note,
};

#[test]
fn test_basic_fvk_workflow() {
    // 1. Create a viewing key (typically generated by an auditor)
    let fvk = FullViewingKey([42u8; 32]);

    // 2. Create a note (sender/recipient creates this)
    let note = Note {
        domain: [1u8; 32],
        value: 1000,
        rho: [2u8; 32],
        recipient: [3u8; 32],
    };

    // 3. Compute the commitment (this goes on-chain)
    let cm = note_commitment(&note.domain, note.value, &note.rho, &note.recipient);

    // 4. Encrypt the note for the FVK holder
    let encrypted = encrypt_note_for_fvk(&fvk, &note, &cm).unwrap();

    // Verify the encrypted note contains the commitment
    assert_eq!(encrypted.cm, cm);

    // 5. Auditor decrypts and verifies the note
    let decrypted = decrypt_and_verify_note(&fvk, &encrypted).unwrap();

    // 6. Verify decrypted note matches original
    assert_eq!(decrypted.domain, note.domain);
    assert_eq!(decrypted.value, note.value);
    assert_eq!(decrypted.rho, note.rho);
    assert_eq!(decrypted.recipient, note.recipient);
}

#[test]
fn test_multiple_notes_same_fvk() {
    let fvk = FullViewingKey([7u8; 32]);

    // Create multiple notes
    let notes = vec![
        Note {
            domain: [1u8; 32],
            value: 100,
            rho: [2u8; 32],
            recipient: [3u8; 32],
        },
        Note {
            domain: [1u8; 32],
            value: 200,
            rho: [4u8; 32],
            recipient: [5u8; 32],
        },
        Note {
            domain: [1u8; 32],
            value: 300,
            rho: [6u8; 32],
            recipient: [7u8; 32],
        },
    ];

    let mut encrypted_notes = Vec::new();

    // Encrypt all notes
    for note in &notes {
        let cm = note_commitment(&note.domain, note.value, &note.rho, &note.recipient);
        let enc = encrypt_note_for_fvk(&fvk, note, &cm).unwrap();
        encrypted_notes.push(enc);
    }

    // Auditor can decrypt all notes
    for (i, enc) in encrypted_notes.iter().enumerate() {
        let decrypted = decrypt_and_verify_note(&fvk, enc).unwrap();
        assert_eq!(decrypted.value, notes[i].value);
    }
}

#[test]
fn test_wrong_fvk_cannot_decrypt() {
    let fvk1 = FullViewingKey([1u8; 32]);
    let fvk2 = FullViewingKey([2u8; 32]);

    let note = Note {
        domain: [1u8; 32],
        value: 500,
        rho: [2u8; 32],
        recipient: [3u8; 32],
    };

    let cm = note_commitment(&note.domain, note.value, &note.rho, &note.recipient);
    let encrypted = encrypt_note_for_fvk(&fvk1, &note, &cm).unwrap();

    // Correct FVK can decrypt
    assert!(decrypt_and_verify_note(&fvk1, &encrypted).is_ok());

    // Wrong FVK cannot decrypt
    assert!(decrypt_and_verify_note(&fvk2, &encrypted).is_err());
}

#[test]
fn test_tampered_ciphertext_rejected() {
    let fvk = FullViewingKey([42u8; 32]);

    let note = Note {
        domain: [1u8; 32],
        value: 1000,
        rho: [2u8; 32],
        recipient: [3u8; 32],
    };

    let cm = note_commitment(&note.domain, note.value, &note.rho, &note.recipient);
    let mut encrypted = encrypt_note_for_fvk(&fvk, &note, &cm).unwrap();

    // Tamper with the ciphertext
    if let Some(byte) = encrypted.ct.get_mut(0) {
        *byte ^= 0xFF;
    }

    // Decryption should fail due to AEAD authentication failure
    let result = decrypt_and_verify_note(&fvk, &encrypted);
    assert!(result.is_err());
}

#[test]
fn test_mismatched_commitment_rejected() {
    let fvk = FullViewingKey([42u8; 32]);

    let note = Note {
        domain: [1u8; 32],
        value: 1000,
        rho: [2u8; 32],
        recipient: [3u8; 32],
    };

    let cm = note_commitment(&note.domain, note.value, &note.rho, &note.recipient);
    let mut encrypted = encrypt_note_for_fvk(&fvk, &note, &cm).unwrap();

    // Change the commitment (simulating a "trust me bro" attack)
    encrypted.cm[0] ^= 1;

    // Decryption should fail because AAD won't match
    let result = decrypt_and_verify_note(&fvk, &encrypted);
    assert!(result.is_err());
}

#[test]
fn test_serialization_roundtrip() {
    let fvk = FullViewingKey([42u8; 32]);

    let note = Note {
        domain: [1u8; 32],
        value: 1000,
        rho: [2u8; 32],
        recipient: [3u8; 32],
    };

    let cm = note_commitment(&note.domain, note.value, &note.rho, &note.recipient);
    let encrypted = encrypt_note_for_fvk(&fvk, &note, &cm).unwrap();

    // Serialize to JSON
    let json = serde_json::to_string(&encrypted).unwrap();

    // Deserialize from JSON
    let deserialized: EncryptedNote = serde_json::from_str(&json).unwrap();

    // Should still be able to decrypt
    let decrypted = decrypt_and_verify_note(&fvk, &deserialized).unwrap();
    assert_eq!(decrypted.value, note.value);
}

#[test]
fn test_borsh_serialization_roundtrip() {
    use borsh::BorshSerialize;

    let fvk = FullViewingKey([42u8; 32]);

    let note = Note {
        domain: [1u8; 32],
        value: 1000,
        rho: [2u8; 32],
        recipient: [3u8; 32],
    };

    let cm = note_commitment(&note.domain, note.value, &note.rho, &note.recipient);
    let encrypted = encrypt_note_for_fvk(&fvk, &note, &cm).unwrap();

    // Serialize to Borsh
    let mut bytes = Vec::new();
    encrypted.serialize(&mut bytes).unwrap();

    // Deserialize from Borsh
    let deserialized = borsh::from_slice::<EncryptedNote>(&bytes).unwrap();

    // Should still be able to decrypt
    let decrypted = decrypt_and_verify_note(&fvk, &deserialized).unwrap();
    assert_eq!(decrypted.value, note.value);
}

#[test]
fn test_fvk_hex_encoding() {
    let fvk = FullViewingKey([42u8; 32]);

    // Serialize to JSON (should use hex encoding)
    let json = serde_json::to_string(&fvk).unwrap();
    
    // Should be hex-encoded string
    assert!(json.contains("\"2a2a2a2a"));

    // Deserialize back
    let deserialized: FullViewingKey = serde_json::from_str(&json).unwrap();
    assert_eq!(deserialized.0, fvk.0);
}

#[test]
fn test_deterministic_nonce_derivation() {
    let fvk = FullViewingKey([42u8; 32]);

    let note = Note {
        domain: [1u8; 32],
        value: 1000,
        rho: [2u8; 32],
        recipient: [3u8; 32],
    };

    let cm = note_commitment(&note.domain, note.value, &note.rho, &note.recipient);

    // Encrypt the same note multiple times
    let enc1 = encrypt_note_for_fvk(&fvk, &note, &cm).unwrap();
    let enc2 = encrypt_note_for_fvk(&fvk, &note, &cm).unwrap();

    // Nonces should be identical (deterministic derivation)
    assert_eq!(enc1.nonce, enc2.nonce);
    
    // Ciphertexts should be identical
    assert_eq!(enc1.ct, enc2.ct);
}

#[test]
fn test_different_fvks_different_ciphertexts() {
    let fvk1 = FullViewingKey([1u8; 32]);
    let fvk2 = FullViewingKey([2u8; 32]);

    let note = Note {
        domain: [1u8; 32],
        value: 1000,
        rho: [2u8; 32],
        recipient: [3u8; 32],
    };

    let cm = note_commitment(&note.domain, note.value, &note.rho, &note.recipient);

    let enc1 = encrypt_note_for_fvk(&fvk1, &note, &cm).unwrap();
    let enc2 = encrypt_note_for_fvk(&fvk2, &note, &cm).unwrap();

    // Different FVKs should produce different ciphertexts
    assert_ne!(enc1.ct, enc2.ct);
    assert_ne!(enc1.nonce, enc2.nonce);
}

/// Test that demonstrates the "not a trust me bro" guarantee:
/// Even if an attacker creates a ciphertext that decrypts, if the
/// plaintext doesn't match the on-chain commitment, it's rejected.
#[test]
fn test_non_truthful_ciphertext_rejected() {
    let fvk = FullViewingKey([42u8; 32]);

    // Attacker creates a note
    let fake_note = Note {
        domain: [1u8; 32],
        value: 999999, // Attacker claims a huge value
        rho: [2u8; 32],
        recipient: [3u8; 32],
    };

    // But the real note has a different value
    let real_note = Note {
        domain: [1u8; 32],
        value: 100, // Actual value
        rho: [2u8; 32],
        recipient: [3u8; 32],
    };

    // The on-chain commitment is for the REAL note
    let real_cm = note_commitment(&real_note.domain, real_note.value, &real_note.rho, &real_note.recipient);

    // Attacker tries to encrypt the FAKE note with the REAL commitment
    // This would work if we didn't verify...
    let encrypted = encrypt_note_for_fvk(&fvk, &fake_note, &real_cm).unwrap();

    // But when we decrypt and verify, the commitment won't match!
    let result = decrypt_and_verify_note(&fvk, &encrypted);
    
    // Should fail with "commitment mismatch: not truthful"
    assert!(result.is_err());
    let err = result.unwrap_err();
    assert!(err.to_string().contains("commitment mismatch"));
}

