[package]
name = "midnight-tx-generator"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "midnight-tx-generator"
path = "src/main.rs"

[[bin]]
name = "midnight-deposit-generator"
path = "src/deposit.rs"

[dependencies]
anyhow = "1.0"
borsh = { version = "1.3", features = ["derive"] }
hex = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
base64 = "0.22"
bincode = "1.3"
rand = "0.8"
ligetron = { git = "https://github.com/dcSpark/ligero-prover.git", rev = "da388b5f5e0ac9e9fcc465acc3e10289e23de1fd", features = ["native"] }

# Local dependencies
sov-modules-api = { path = "../../crates/module-system/sov-modules-api" }
sov-modules-rollup-blueprint = { path = "../../crates/module-system/sov-modules-rollup-blueprint" }
sov-cli = { path = "../../crates/module-system/sov-cli" }
demo-stf = { path = "../../examples/demo-rollup/stf", features = ["native"] }
sov-rollup-ligero = { path = "../../examples/rollup-ligero" }
midnight-privacy = { path = "../../crates/module-system/module-implementations/midnight-privacy", features = ["native"] }
sov-test-utils = { path = "../../crates/module-system/sov-test-utils" }
sov-ligero-adapter = { path = "../../crates/adapters/ligero", features = ["native"] }
sov-rollup-interface = { path = "../../crates/rollup-interface" }
sov-node-client = { path = "../../crates/utils/sov-node-client" }
sov-bank = { path = "../../crates/module-system/module-implementations/sov-bank", features = ["native"] }
tokio = { version = "1.36", features = ["rt-multi-thread", "macros"] }
reqwest = { version = "0.11", default-features = false, features = ["json", "rustls-tls", "blocking"] }


[[bin]]
name = "withdraw-with-tree"
path = "src/withdraw_with_tree.rs"

[[bin]]
name = "transfer-generator"
path = "src/transfer_generator.rs"

[[bin]]
name = "withdraw-generator"
path = "src/withdraw_generator.rs"

[[bin]]
name = "fetch-nonce"
path = "src/fetch_nonce.rs"

[[bin]]
name = "fund"
path = "src/fund.rs"
