#!/bin/bash
set -e

GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

GENERATOR_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$GENERATOR_DIR/../.." && pwd)"

# Get unique nonce based on timestamp
NONCE=$(date +%s)
DEPOSIT_AMOUNT="${DEPOSIT_AMOUNT:-100}"
WITHDRAW_AMOUNT="${WITHDRAW_AMOUNT:-50}"
PRIVATE_KEY_FILE="${PRIVATE_KEY_FILE:-$REPO_ROOT/examples/test-data/keys/tx_signer_private_key.json}"
RECIPIENT="${RECIPIENT:-sov1v870parxhssv5wyz634wqlt9yflrrnawlwzjhj8409q4yevcj3s}"

# Endpoint - proof verifier service orchestrates sequencer submissions
VERIFIER_ENDPOINT="${VERIFIER_ENDPOINT:-http://localhost:8080/midnight-privacy}"

echo -e "${BLUE}=== Midnight Privacy: Deposit + Withdraw Flow ===${NC}\n"
echo "Parameters:"
echo "  Deposit: $DEPOSIT_AMOUNT"
echo "  Withdraw: $WITHDRAW_AMOUNT"
echo "  Change: $((DEPOSIT_AMOUNT - WITHDRAW_AMOUNT)) (stays shielded)"
echo "  Nonce: $NONCE"
echo "  Proof Verifier: $VERIFIER_ENDPOINT"
echo ""

# Build generators if needed
if [ ! -f "$GENERATOR_DIR/target/debug/midnight-deposit-generator" ] || [ ! -f "$GENERATOR_DIR/target/debug/midnight-tx-generator" ]; then
    echo -e "${YELLOW}Building generators...${NC}"
    cd "$GENERATOR_DIR"
    SKIP_GUEST_BUILD=1 cargo build --bin midnight-deposit-generator --bin midnight-tx-generator 2>&1 | grep -E "Compiling|Finished" || true
    cd "$REPO_ROOT"
    echo ""
fi

# Step 1: Generate and send deposit
echo -e "${YELLOW}Step 1: Deposit${NC}"
export DEPOSIT_AMOUNT NONCE PRIVATE_KEY_FILE
cd "$GENERATOR_DIR"
"$GENERATOR_DIR/target/debug/midnight-deposit-generator" "midnight_deposit_tx.bin" > /tmp/deposit.log
cd "$REPO_ROOT"

# Send deposit to proof verifier (which forwards to sequencer)
DEPOSIT_RESPONSE=$(curl -s -4 -X POST \
  -H "Content-Type: application/json" \
  -d @"$GENERATOR_DIR/midnight_deposit_tx.json" \
  "$VERIFIER_ENDPOINT")

echo "$DEPOSIT_RESPONSE" | jq '.' 2>/dev/null || echo "$DEPOSIT_RESPONSE"

DEPOSIT_SUCCESS=$(echo "$DEPOSIT_RESPONSE" | jq -r '.success // empty')
if [ "$DEPOSIT_SUCCESS" != "true" ]; then
    ERROR_MSG=$(echo "$DEPOSIT_RESPONSE" | jq -r '.error // empty')
    if [ -n "$ERROR_MSG" ] && [ "$ERROR_MSG" != "null" ]; then
        echo -e "${RED}✗ Deposit failed: $ERROR_MSG${NC}"
    else
        echo -e "${RED}✗ Deposit failed${NC}"
    fi
    exit 1
fi

SEQUENCER_RESPONSE=$(echo "$DEPOSIT_RESPONSE" | jq -c '.sequencer_response // empty')
if [ -z "$SEQUENCER_RESPONSE" ] || [ "$SEQUENCER_RESPONSE" = "null" ]; then
    echo -e "${RED}✗ Sequencer response missing from deposit result${NC}"
    exit 1
fi

# Extract position and anchor root from deposit response
NOTE_POSITION=$(echo "$SEQUENCER_RESPONSE" | jq -r '.events[] | select(.key == "ValueMidnightPrivacy/PoolDeposit") | .value.pool_deposit.position')
ANCHOR_ROOT=$(echo "$SEQUENCER_RESPONSE" | jq -c '.events[] | select(.key == "ValueMidnightPrivacy/PoolDeposit") | .value.pool_deposit.new_root')

if [ -z "$NOTE_POSITION" ] || [ "$NOTE_POSITION" = "null" ]; then
    echo -e "${RED}✗ Failed to extract note position from deposit response${NC}"
    exit 1
fi

echo -e "${GREEN}✓ Deposit sent${NC}"
echo "  Note position: $NOTE_POSITION"
echo "  Anchor root: $(echo $ANCHOR_ROOT | jq -r 'if type == "array" then (.[0:8] | map(tostring) | join(",")) else . end')"
echo ""

# Wait for confirmation
echo -e "${YELLOW}Waiting 3 seconds for confirmation...${NC}"
sleep 3
echo ""

# Step 2: Generate and send withdrawal
echo -e "${YELLOW}Step 2: Withdraw${NC}"

# Increment nonce for withdrawal
WITHDRAW_NONCE=$((NONCE + 1))

# Load note details
NOTE_DETAILS_FILE="$GENERATOR_DIR/midnight_note_details.json"
NOTE_DOMAIN=$(cat "$NOTE_DETAILS_FILE" | jq -r '.domain')
NOTE_VALUE=$(cat "$NOTE_DETAILS_FILE" | jq -r '.amount')
NOTE_RHO=$(cat "$NOTE_DETAILS_FILE" | jq -r '.rho')
NOTE_RECIPIENT=$(cat "$NOTE_DETAILS_FILE" | jq -r '.recipient')
NOTE_NF_KEY=$(cat "$NOTE_DETAILS_FILE" | jq -r '.nf_key')

# Create withdrawal generator with real tree data
cat > /tmp/withdraw_with_tree.rs << 'EOFRS'
use anyhow::{Context, Result};
use base64::Engine;
use borsh;
use hex;
use demo_stf::runtime::{Runtime, RuntimeCall};
use midnight_privacy::{note_commitment, nullifier, CallMessage, Hash32, SpendPublic};
use rand::Rng;
use serde_json;
use sov_cli::wallet_state::PrivateKeyAndAddress;
use sov_demo_rollup::MockDemoRollup;
use sov_ligero_adapter::Ligero;
use sov_modules_api::execution_mode::Native;
use sov_modules_api::transaction::Transaction;
use sov_modules_api::{CryptoSpec, PrivateKey, Spec};
use sov_modules_rollup_blueprint::RollupBlueprint;
use sov_rollup_interface::zk::{Zkvm, ZkvmHost};
use sov_test_utils::default_test_signed_transaction;
use std::fs;

type DemoRollupSpec = <MockDemoRollup<Native> as RollupBlueprint<Native>>::Spec;

mod demo_generated {
    include!("../../../examples/demo-rollup/autogenerated.rs");
}

const CHAIN_HASH: [u8; 32] = demo_generated::CHAIN_HASH;

fn main() -> Result<()> {
    let domain: Hash32 = hex::decode(std::env::var("NOTE_DOMAIN")?)?
        .try_into().map_err(|_| anyhow::anyhow!("Invalid domain"))?;
    let value: u128 = std::env::var("NOTE_VALUE")?.parse()?;
    let rho: Hash32 = hex::decode(std::env::var("NOTE_RHO")?)?
        .try_into().map_err(|_| anyhow::anyhow!("Invalid rho"))?;
    let recipient: Hash32 = hex::decode(std::env::var("NOTE_RECIPIENT")?)?
        .try_into().map_err(|_| anyhow::anyhow!("Invalid recipient"))?;
    let nf_key: Hash32 = hex::decode(std::env::var("NOTE_NF_KEY")?)?
        .try_into().map_err(|_| anyhow::anyhow!("Invalid nf_key"))?;
    let withdraw_amount: u128 = std::env::var("WITHDRAW_AMOUNT")?.parse()?;
    let position: u64 = std::env::var("NOTE_POSITION")?.parse()?;
    let nonce: u64 = std::env::var("NONCE")?.parse()?;
    let recipient_addr: String = std::env::var("RECIPIENT")?;
    
    // Get the actual anchor root from the deposit response
    let anchor_bytes: Vec<u8> = serde_json::from_str(&std::env::var("ANCHOR_ROOT")?)?;
    let anchor: Hash32 = anchor_bytes.try_into().map_err(|_| anyhow::anyhow!("Invalid anchor"))?;
    
    // Compute the note commitment
    let cm = note_commitment(&domain, value, &rho, &recipient);
    let nf = nullifier(&domain, &nf_key, &rho);
    
    // Build a Merkle tree with the note at the actual position
    // and get the authentication path
    use midnight_privacy::MerkleTree;
    let tree_depth: u8 = 16;
    let mut tree = MerkleTree::new(tree_depth);
    tree.set_leaf(position as usize, cm);
    let siblings = tree.open(position as usize);
    
    println!("Note commitment: 0x{}", hex::encode(&cm[..8]));
    println!("Position: {}", position);
    println!("Anchor root (from deposit): 0x{}", hex::encode(&anchor[..8]));
    println!("Nullifier: 0x{}", hex::encode(&nf[..8]));
    
    let change_value = value - withdraw_amount;
    let out_rho: Hash32 = rand::thread_rng().gen();
    let out_recipient: Hash32 = rand::thread_rng().gen();
    let cm_out = note_commitment(&domain, change_value, &out_rho, &out_recipient);
    
    let public_output = SpendPublic {
        anchor_root: anchor,
        nullifier: nf,
        withdraw_amount,
        output_commitments: vec![cm_out],
    };
    
    let program_path = std::env::var("LIGERO_PROGRAM_PATH")?;
    let packing: u32 = std::env::var("LIGERO_PACKING")?.parse()?;
    
    let mut private_indices = vec![2, 3, 4, 5, 6];
    for i in 0..tree_depth as usize { private_indices.push(8 + i); }
    let base = 12 + tree_depth as usize;
    private_indices.extend(&[base, base + 1, base + 2]);
    
    let mut host = <Ligero as Zkvm>::Host::from_args(&program_path)
        .with_packing(packing)
        .with_private_indices(private_indices);
    
    host.add_hex_arg(hex::encode(domain));
    host.add_str_arg(value.to_string());
    host.add_hex_arg(hex::encode(rho));
    host.add_hex_arg(hex::encode(recipient));
    host.add_hex_arg(hex::encode(nf_key));
    host.add_str_arg(position.to_string());
    host.add_str_arg(tree_depth.to_string());
    
    for sibling in &siblings {
        host.add_hex_arg(hex::encode(sibling));
    }
    
    host.add_hex_arg(hex::encode(anchor));
    host.add_hex_arg(hex::encode(nf));
    host.add_str_arg(withdraw_amount.to_string());
    host.add_str_arg("1".to_string());
    host.add_str_arg(change_value.to_string());
    host.add_hex_arg(hex::encode(out_rho));
    host.add_hex_arg(hex::encode(out_recipient));
    host.add_hex_arg(hex::encode(cm_out));
    
    host.set_public_output(&public_output)?;
    
    println!("Generating proof...");
    let proof_bytes = host.run(true)?;
    println!("✓ Proof: {} bytes", proof_bytes.len());
    
    let recipient_parsed: <DemoRollupSpec as Spec>::Address = recipient_addr.parse()?;
    let key_data: PrivateKeyAndAddress<DemoRollupSpec> = 
        serde_json::from_str(&fs::read_to_string(std::env::var("PRIVATE_KEY_FILE")?)?)?;
    
    let proof_safe = proof_bytes.try_into()
        .map_err(|_| anyhow::anyhow!("Proof too large"))?;
    
    let msg = RuntimeCall::<DemoRollupSpec>::MidnightPrivacy(
        CallMessage::Withdraw {
            proof: proof_safe,
            anchor_root: anchor,
            nullifier: nf,
            withdraw_amount,
            to: recipient_parsed,
            gas: None,
        }
    );
    
    let tx: Transaction<Runtime<DemoRollupSpec>, DemoRollupSpec> = 
        default_test_signed_transaction(&key_data.private_key, &msg, nonce, &CHAIN_HASH);
    
    let tx_bytes = borsh::to_vec(&tx)?;
    fs::write("midnight_withdraw_tx.bin", &tx_bytes)?;
    
    let tx_base64 = base64::engine::general_purpose::STANDARD.encode(&tx_bytes);
    fs::write("midnight_withdraw_tx.json", 
        serde_json::to_string_pretty(&serde_json::json!({"body": tx_base64}))?)?;
    
    println!("✓ Transaction: {} bytes", tx_bytes.len());
    Ok(())
}
EOFRS

# Update Cargo.toml to include the withdrawal script
cd "$GENERATOR_DIR"
if ! grep -q "withdraw-with-tree" Cargo.toml; then
    cat >> Cargo.toml << 'EOF'

[[bin]]
name = "withdraw-with-tree"
path = "src/withdraw_with_tree.rs"
EOF
fi

mv /tmp/withdraw_with_tree.rs src/
SKIP_GUEST_BUILD=1 cargo build --bin withdraw-with-tree 2>&1 | grep -E "Compiling|Finished" || true
cd "$REPO_ROOT"

# Set environment and generate withdrawal
# Set LIGERO environment for proof generation
export LIGERO_PROGRAM_PATH="$REPO_ROOT/crates/adapters/ligero/guest/bins/programs/note_spend_guest.wasm"
export LIGERO_PACKING=8192
if [[ "$OSTYPE" == "darwin"* ]]; then
    export LIGERO_SHADER_PATH="$REPO_ROOT/crates/adapters/ligero/bins/macos/shader"
else
    export LIGERO_SHADER_PATH="$REPO_ROOT/crates/adapters/ligero/bins/linux-amd64/shader"
fi

export NOTE_DOMAIN NOTE_VALUE NOTE_RHO NOTE_RECIPIENT NOTE_NF_KEY
export WITHDRAW_AMOUNT RECIPIENT
export NOTE_POSITION
export ANCHOR_ROOT
export NONCE=$WITHDRAW_NONCE
export PRIVATE_KEY_FILE

cd "$GENERATOR_DIR"
"$GENERATOR_DIR/target/debug/withdraw-with-tree" 2>&1 | tee /tmp/withdraw.log
cd "$REPO_ROOT"

# Send withdrawal to proof verifier (which forwards to sequencer)
WITHDRAW_RESPONSE=$(curl -s -4 -X POST \
  -H "Content-Type: application/json" \
  -d @"$GENERATOR_DIR/midnight_withdraw_tx.json" \
  "$VERIFIER_ENDPOINT")

echo "$WITHDRAW_RESPONSE" | jq '.' 2>/dev/null || echo "$WITHDRAW_RESPONSE"

WITHDRAW_SUCCESS=$(echo "$WITHDRAW_RESPONSE" | jq -r '.success // empty')
if [ "$WITHDRAW_SUCCESS" != "true" ]; then
    ERROR_MSG=$(echo "$WITHDRAW_RESPONSE" | jq -r '.error // empty')
    if [ -n "$ERROR_MSG" ] && [ "$ERROR_MSG" != "null" ]; then
        echo -e "${RED}✗ Withdrawal failed: $ERROR_MSG${NC}"
    else
        echo -e "${RED}✗ Withdrawal failed${NC}"
    fi
    exit 1
fi

echo -e "${GREEN}✓ Withdrawal sent${NC}\n"
echo -e "${GREEN}=== Success! ===${NC}"
echo "  Deposited: $DEPOSIT_AMOUNT"
echo "  Withdrew: $WITHDRAW_AMOUNT (transparent)"
echo "  Change: $((DEPOSIT_AMOUNT - WITHDRAW_AMOUNT)) (stays in shielded pool)"
