[package]
name = "midnight-privacy"
description = "Midnight Privacy Module"
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

version = { workspace = true }
readme = "README.md"
publish = false

[lints]
workspace = true

[dev-dependencies]
sov-address = { workspace = true }
tempfile = { workspace = true }
sov-modules-api = { workspace = true, features = ["native"] }
sov-test-utils = { workspace = true }
sov-state = { workspace = true, features = ["native"] }
sha2 = { workspace = true }
sov-ligero-adapter = { workspace = true, features = ["native"] }
sov-rollup-interface = { workspace = true, features = ["native"] }
hex = { workspace = true }
serde_json = { workspace = true }
sov-bank = { workspace = true, features = ["native", "test-utils"] }

[dependencies]
anyhow = { workspace = true }
sov-modules-api = { workspace = true }
sov-rollup-interface = { workspace = true }
sov-ligero-adapter = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
borsh = { workspace = true, features = ["rc"] }
sov-state = { workspace = true }
bincode = { workspace = true }
hex = { workspace = true }
qp-poseidon-core = { version = "0.9.5", features = ["std"] }
sov-bank = { workspace = true }
once_cell = { workspace = true }
chacha20poly1305 = { version = "0.10", features = ["std"] }
hkdf = "0.12"
sha2 = { workspace = true }

[features]
default = ["native"]
native = [
    "sov-modules-api/native",
    "sov-rollup-interface/native",
    "sov-state/native",
    "sov-address/native",
    "sov-ligero-adapter/native"
]

