[package]
name = "tee"
description = "Library that generate and verifies TEE attestations."
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
version = "0.2.0"

[dependencies]
anyhow = { workspace = true }
serde_json = { workspace = true }
sev = { version = "=1.2.1", optional = true, default-features = false }
az-snp-vtpm = { optional = true, version = "=0.6.0", default-features = false }
base64 = { version = "=0.22.1" }
borsh = { workspace = true }
serde = { workspace = true, features = ["derive"] }
sha2 = { version = "=0.10.9" }
alloy-primitives = { workspace = true, features = ["borsh", "serde"] }
jsonwebtoken = { optional = true, version = "=10.2.0", features = ["aws_lc_rs"] }
reqwest = { workspace = true, features = ["json", "rustls-tls", "blocking"] }
tss-esapi = "=7.5.1"
webpki-roots = "=0.26.3"
serde-big-array = "=0.5.1"
rustls-webpki = "=0.102.5"
memoffset = "=0.9.1"
ring = "=0.17.8"
bincode = "=1.3.3"
openssl = "=0.10.64"
binrw = "=0.14.0"
tempfile = "=3.27.0"
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }

[dev-dependencies]
tokio = { workspace = true, features = ["full"] }
fake-attestation-server = { workspace = true }

[features]
# Microsoft Azure Attestation
maa = ["dep:jsonwebtoken", "dep:az-snp-vtpm"]
# Azure HCL report
az_hcl = ["dep:az-snp-vtpm"]
# Raw SEV.
sev = ["dep:sev"]
# Default features
default = []

[lints]
workspace = true
