use demo_stf::runtime::Runtime;
use sov_address::MultiAddressEvm;
use sov_ligero_adapter::Ligero;
use sov_midnight_da::MidnightDaSpec;
use sov_mock_zkvm::MockZkvm;
use sov_modules_api::execution_mode::Native;
use sov_zkvm_utils::should_skip_guest_build;

fn main() -> anyhow::Result<()> {
    println!("cargo::rerun-if-env-changed=SKIP_GUEST_BUILD");
    println!("cargo::rerun-if-env-changed=SOV_PROVER_MODE");
    println!("cargo::rerun-if-env-changed=GIT_COMMIT_HASH");
    println!("cargo::rustc-check-cfg=cfg(skip_guest_build)");
    println!("cargo:rerun-if-changed=NULL");

    // It will be true only if SKIP_GUEST_BUILD is 1 or true
    if should_skip_guest_build("any-zkvm") {
        println!("cargo::rustc-cfg=skip_guest_build");
    }

    type S = sov_modules_api::configurable_spec::ConfigurableSpec<
        MidnightDaSpec,
        Ligero,
        MockZkvm,
        MultiAddressEvm,
        Native,
    >;

    let git_hash_from_env = std::env::var("GIT_COMMIT_HASH")
        .ok()
        .filter(|hash| !hash.trim().is_empty());
    if let Some(hash) = &git_hash_from_env {
        println!("cargo:rustc-env=GIT_COMMIT_HASH={hash}");
    }

    sov_build::Options::builder()
        .rust_autogenerated_path("autogenerated.rs")
        .set_git_hash(git_hash_from_env.is_none())
        .json_schema(false)
        .build()
        .apply::<S, Runtime<S>>()
}
