use base64::{prelude::BASE64_STANDARD, Engine};
use sea_orm::{ConnectOptions, Database, EntityTrait};
use sov_address::EthereumAddress;
use sov_modules_api::transaction::{PriorityFeeBips, Transaction, TxDetails, UnsignedTransaction, VersionedTx};
use sov_modules_api::{Amount, SafeVec};
use sov_modules_api::capabilities::UniquenessData;
use sov_proof_verifier_service::*;
use std::str::FromStr;

use demo_stf::runtime::Runtime as DemoRuntime;
use midnight_privacy::{CallMessage as MidnightCallMessage, SpendPublic};
use sov_address::MultiAddressEvm;
use sov_midnight_da::storable::{setup_db as setup_midnight_da_db, worker_verified_transactions, IncomingWorkerTxSaver};
use sov_rollup_interface::{crypto::PrivateKey, zk::CryptoSpec};
use sov_modules_api::Spec;

// Import the rollup spec and runtime types from the service
type RollupSpec = sov_proof_verifier_service::RollupSpec;

mod rollup_autogen {
    include!("../../../../examples/rollup-ligero/autogenerated.rs");
}

const ROLLUP_CHAIN_HASH: [u8; 32] = rollup_autogen::CHAIN_HASH;

// Use the runtime call type alias for cleaner code
type RuntimeCall = <DemoRuntime<RollupSpec> as sov_modules_api::DispatchCall>::Decodable;

fn sample_midnight_withdraw_transaction(
    nonce: u64,
) -> Transaction<DemoRuntime<RollupSpec>, RollupSpec> {
    let signing_key = <<RollupSpec as Spec>::CryptoSpec as CryptoSpec>::PrivateKey::generate();
    let anchor_root = [42u8; 32];
    let nullifier = [7u8; 32];
    let withdraw_amount = 123_456u128;
    let to = MultiAddressEvm::Vm(
        EthereumAddress::from_str("0x71334bf1710D12c9f689cC819476fA589F08C64C").unwrap(),
    );
    let proof = SafeVec::try_from(vec![9u8; 16]).expect("within SafeVec capacity");

    let call = MidnightCallMessage::<RollupSpec>::Withdraw {
        proof,
        anchor_root,
        nullifier,
        withdraw_amount,
        to,
        view_ciphertexts: None,
        gas: None,
    };

    let details = TxDetails {
        max_fee: Amount::from(100_000_000_000u128),
        max_priority_fee_bips: PriorityFeeBips(0),
        gas_limit: None,
        chain_id: 4321,
    };

    let runtime_call = RuntimeCall::MidnightPrivacy(call);
    let unsigned_tx = UnsignedTransaction::new_with_details(
        runtime_call,
        UniquenessData::Generation(nonce),
        details,
    );

    Transaction::<DemoRuntime<RollupSpec>, RollupSpec>::new_signed_tx(
        &signing_key,
        &ROLLUP_CHAIN_HASH,
        unsigned_tx,
    )
}

fn sample_midnight_deposit_transaction(nonce: u64) -> Transaction<DemoRuntime<RollupSpec>, RollupSpec> {
    let signing_key = <<RollupSpec as Spec>::CryptoSpec as CryptoSpec>::PrivateKey::generate();
    let rho = [99u8; 32];
    let recipient = [100u8; 32];

    let call = MidnightCallMessage::<RollupSpec>::Deposit {
        amount: 100u128,
        rho,
        recipient,
        view_fvks: None,
        gas: None,
    };

    let details = TxDetails {
        max_fee: Amount::from(100_000_000_000u128),
        max_priority_fee_bips: PriorityFeeBips(0),
        gas_limit: None,
        chain_id: 4321,
    };

    let runtime_call = RuntimeCall::MidnightPrivacy(call);
    let unsigned_tx = UnsignedTransaction::new_with_details(
        runtime_call,
        UniquenessData::Generation(nonce),
        details,
    );

    Transaction::<DemoRuntime<RollupSpec>, RollupSpec>::new_signed_tx(
        &signing_key,
        &ROLLUP_CHAIN_HASH,
        unsigned_tx,
    )
}

#[test]
fn test_value_setter_call_serialization() {
    let call = ValueSetterCall::SetValue {
        value: 42,
        gas: None,
    };

    let bytes = borsh::to_vec(&call).unwrap();
    assert!(!bytes.is_empty());

    let deserialized: ValueSetterCall = borsh::from_slice(&bytes).unwrap();
    match deserialized {
        ValueSetterCall::SetValue { value, .. } => assert_eq!(value, 42),
        _ => panic!("Wrong variant"),
    }
}

#[test]
fn test_parse_midnight_withdraw_call_roundtrips() {
    let tx = sample_midnight_withdraw_transaction(0);
    let (proof_bytes, anchor_root, nullifier, withdraw_amount, recipient, _view_ciphertexts) =
        parse_midnight_withdraw_call(&tx).expect("parse succeeds");

    assert_eq!(proof_bytes.len(), 16);
    assert_eq!(anchor_root, [42u8; 32]);
    assert_eq!(nullifier, [7u8; 32]);
    assert_eq!(withdraw_amount, 123_456u128);
    assert_eq!(
        recipient,
        MultiAddressEvm::Vm(
            EthereumAddress::from_str("0x71334bf1710D12c9f689cC819476fA589F08C64C").unwrap()
        )
    );
}

#[test]
fn test_verify_midnight_transaction_signature_accepts_valid() {
    let tx = sample_midnight_withdraw_transaction(5);
    verify_midnight_transaction_signature(&tx).expect("signature valid");
}

#[test]
fn test_verify_midnight_transaction_signature_rejects_tampered() {
    let mut tx = sample_midnight_withdraw_transaction(7);
    let VersionedTx::V0(inner) = &mut tx.versioned_tx;
    if let RuntimeCall::MidnightPrivacy(MidnightCallMessage::Withdraw {
        ref mut withdraw_amount,
        ..
    }) = inner.runtime_call
    {
        *withdraw_amount += 1;
    }

    match verify_midnight_transaction_signature(&tx) {
        Err(ServiceError::SignatureError(_)) => {}
        other => panic!("expected signature error, got {other:?}"),
    }
}

#[tokio::test]
async fn test_store_verified_midnight_transaction_upsert() {
    let mut opts = ConnectOptions::new("sqlite::memory:".to_string());
    opts.max_connections(1).sqlx_logging(false);
    let conn = Database::connect(opts).await.unwrap();
    setup_midnight_da_db(&conn).await.unwrap();

    let tx = sample_midnight_withdraw_transaction(9);
    let tx_hash = tx.hash().to_string();
    let tx_json = create_transaction_without_proof(&tx).unwrap();
    let full_blob = BASE64_STANDARD.encode(borsh::to_vec(&tx).unwrap());
    let mut proof_public = SpendPublic {
        anchor_root: [1u8; 32],
        nullifier: [2u8; 32],
        withdraw_amount: 55,
        output_commitments: vec![],
        view_attestations: None,
    };
    let saver = IncomingWorkerTxSaver::disabled();
    store_verified_midnight_transaction(
        &conn,
        &saver,
        &tx_hash,
        Some(&proof_public),
        true,
        Some(true),
        &tx_json,
        &full_blob,
        None,
        None,
    )
        .await
        .unwrap();

    proof_public.withdraw_amount = 99;
    store_verified_midnight_transaction(
        &conn,
        &saver,
        &tx_hash,
        Some(&proof_public),
        true,
        Some(true),
        &tx_json,
        &full_blob,
        None,
        None,
    )
        .await
        .unwrap();

    let stored = worker_verified_transactions::Entity::find()
        .all(&conn)
        .await
        .unwrap();
    assert_eq!(stored.len(), 1);
    let record = &stored[0];
    assert_eq!(record.tx_hash, tx_hash);
    assert!(record.signature_valid);
    assert_eq!(record.proof_verified, Some(true));
    
    // Verify proof outputs are stored as JSON
    let proof_outputs: SpendPublic = serde_json::from_str(&record.proof_outputs).unwrap();
    assert_eq!(proof_outputs.withdraw_amount, proof_public.withdraw_amount);
    assert_eq!(proof_outputs.anchor_root, proof_public.anchor_root);
    assert_eq!(proof_outputs.nullifier, proof_public.nullifier);
    assert_eq!(record.transaction_data, tx_json);
}

#[tokio::test]
async fn test_store_deposit_transaction_without_proof() {
    let mut opts = ConnectOptions::new("sqlite::memory:".to_string());
    opts.max_connections(1).sqlx_logging(false);
    let conn = Database::connect(opts).await.unwrap();
    setup_midnight_da_db(&conn).await.unwrap();

    let tx = sample_midnight_deposit_transaction(11);
    let tx_hash = tx.hash().to_string();
    let transaction_data = create_transaction_without_proof(&tx).unwrap();
    let full_blob = BASE64_STANDARD.encode(borsh::to_vec(&tx).unwrap());

    // Store deposit with no proof
    let saver = IncomingWorkerTxSaver::disabled();
    store_verified_midnight_transaction(
        &conn,
        &saver,
        &tx_hash,
        None,       // No proof outputs for deposits
        true,       // signature_valid
        None,       // proof_verified: NULL (transaction doesn't have a proof)
        &transaction_data,
        &full_blob,
        None,       // No pre-auth data in test
        None,       // No encrypted notes for deposits (they use view_fvks instead)
    )
    .await
    .unwrap();

    let stored = worker_verified_transactions::Entity::find()
        .all(&conn)
        .await
        .unwrap();
    assert_eq!(stored.len(), 1);
    
    let record = &stored[0];
    assert_eq!(record.tx_hash, tx_hash);
    assert!(record.signature_valid, "Signature should be valid");
    assert_eq!(record.proof_verified, None, "proof_verified should be NULL for deposits");
    assert_eq!(record.proof_outputs, "{}", "proof_outputs should be empty JSON for deposits");
    assert_eq!(record.transaction_data, transaction_data);
}

#[tokio::test]
async fn test_verify_midnight_withdraw_proof_invalid_payload() {
    let proof = vec![0u8; 4];
    let anchor_root = [3u8; 32];
    let nullifier = [4u8; 32];
    let withdraw_amount = 77u128;

    match verify_midnight_withdraw_proof(
        Some([0u8; 32]).as_ref(),
        &proof,
        anchor_root,
        nullifier,
        withdraw_amount,
        None,
    )
    .await
    {
        // Either ProofError (if WASM file exists) or Internal error (if WASM file not found)
        Err(ServiceError::ProofError(_)) => {
            // Expected: proof is invalid
        }
        Err(ServiceError::Internal(msg)) if msg.contains("note_spend_guest.wasm") => {
            // Also acceptable in test environment: WASM file not found
            // This means we can't even attempt proof verification
        }
        Err(ServiceError::Internal(msg)) if msg.contains("LIGERO_VERIFIER_BIN") => {
            // Also acceptable in test environment: verifier binary not configured
        }
        other => panic!("expected proof error or missing WASM file, got {other:?}"),
    }
}

/// End-to-end test that mimics the generate_and_send_midnight_tx.sh script
/// 
/// This test validates the core workflow:
/// 1. Transaction creation and serialization (like midnight-tx-generator)
/// 2. Signature verification
/// 3. Proof verification (mocked, since we don't have Ligero in test env)
/// 4. Database storage
/// 5. Database content verification
#[tokio::test]
async fn test_end_to_end_midnight_withdrawal_flow() {
    println!("\n=== Midnight Withdrawal E2E Test ===\n");
    
    // Step 1: Setup database (mimics shared MockDA database)
    let mut db_opts = ConnectOptions::new("sqlite::memory:".to_string());
    db_opts.max_connections(10).sqlx_logging(false);
    let conn = Database::connect(db_opts).await.unwrap();
    setup_midnight_da_db(&conn).await.unwrap();
    println!("✓ Step 1: Database initialized");
    let saver = IncomingWorkerTxSaver::disabled();

    // Step 2: Generate a midnight withdrawal transaction (like midnight-tx-generator does)
    println!("\n✓ Step 2: Creating transaction (like midnight-tx-generator)");
    
    let anchor_root = [0u8; 32]; // All zeros like the script default
    let nullifier = [0u8; 32];
    let withdraw_amount = 500u128; // Matches script default
    let recipient = MultiAddressEvm::Vm(
        EthereumAddress::from_str("0x71334bf1710D12c9f689cC819476fA589F08C64C").unwrap(),
    );
    
    // Use a small dummy proof (real proof is ~8MB from Ligero)
    let dummy_proof = SafeVec::try_from(vec![0u8; 32]).expect("within SafeVec capacity");

    let signing_key = <<RollupSpec as Spec>::CryptoSpec as CryptoSpec>::PrivateKey::generate();
    
    let call = MidnightCallMessage::<RollupSpec>::Withdraw {
        proof: dummy_proof,
        anchor_root,
        nullifier,
        withdraw_amount,
        to: recipient.clone(),
        view_ciphertexts: None,
        gas: None,
    };

    let details = TxDetails {
        max_fee: Amount::from(100_000_000_000u128),
        max_priority_fee_bips: PriorityFeeBips(0),
        gas_limit: None,
        chain_id: 4321,
    };

    let runtime_call = RuntimeCall::MidnightPrivacy(call);
    let unsigned_tx = UnsignedTransaction::new_with_details(
        runtime_call,
        UniquenessData::Generation(0),
        details,
    );

    let tx = Transaction::<DemoRuntime<RollupSpec>, RollupSpec>::new_signed_tx(
        &signing_key,
        &ROLLUP_CHAIN_HASH,
        unsigned_tx,
    );

    let tx_hash = tx.hash().to_string();
    println!("  Transaction Hash: {}", tx_hash);
    println!("  Anchor Root: 0x{}", hex::encode(anchor_root));
    println!("  Nullifier: 0x{}", hex::encode(nullifier));
    println!("  Withdraw Amount: {}", withdraw_amount);
    println!("  Recipient: {:?}", recipient);

    // Step 3: Serialize to bytes and encode as base64 (like the shell script does)
    let tx_bytes = borsh::to_vec(&tx).expect("Failed to serialize transaction");
    let tx_base64 = BASE64_STANDARD.encode(&tx_bytes);
    println!("\n✓ Step 3: Transaction serialized");
    println!("  Binary: {} bytes", tx_bytes.len());
    println!("  Base64: {} chars", tx_base64.len());

    // Step 4: SIGNATURE VERIFICATION (key test!)
    println!("\n✓ Step 4: Testing signature verification");
    verify_midnight_transaction_signature(&tx)
        .expect("Signature should be valid");
    println!("  ✓ Signature verified successfully!");

    // Step 5: Parse the transaction (extract proof, anchor_root, nullifier, etc.)
    println!("\n✓ Step 5: Testing transaction parsing");
    let (proof_bytes, parsed_anchor_root, parsed_nullifier, parsed_amount, parsed_recipient, _view_ciphertexts) =
        parse_midnight_withdraw_call(&tx).expect("Should parse transaction");
    
    assert_eq!(proof_bytes.len(), 32, "Proof should be our dummy 32 bytes");
    assert_eq!(parsed_anchor_root, anchor_root, "Anchor root should match");
    assert_eq!(parsed_nullifier, nullifier, "Nullifier should match");
    assert_eq!(parsed_amount, withdraw_amount, "Withdraw amount should match");
    assert_eq!(parsed_recipient, recipient, "Recipient should match");
    println!("  ✓ All fields parsed correctly!");

    // Step 6: PROOF VERIFICATION (mocked)
    // In production, this would call verify_midnight_withdraw_proof with real Ligero
    // For this test, we simulate the proof output that would be returned
    println!("\n✓ Step 6: Simulating proof verification");
    let simulated_proof_output = SpendPublic {
        anchor_root,
        nullifier,
        withdraw_amount,
        output_commitments: vec![],
        view_attestations: None,
    };
    println!("  ✓ Proof verification simulated (would verify with Ligero in production)");
    
    // Step 7: DATABASE STORAGE (key test!)
    println!("\n✓ Step 7: Testing database storage");
    let transaction_data = create_transaction_without_proof(&tx)
        .expect("Should create transaction data");
    
    store_verified_midnight_transaction(
        &conn,
        &saver,
        &tx_hash,
        Some(&simulated_proof_output),
        true,          // signature_valid
        Some(true),    // proof_verified (has proof and verified)
        &transaction_data,
        &tx_base64, // full transaction blob
        None,          // No pre-auth data in test
        None,          // No encrypted notes in test
    )
    .await
    .expect("Should store to database");
    println!("  ✓ Transaction stored to database!");

    // Step 8: DATABASE VERIFICATION (key test!)
    println!("\n✓ Step 8: Verifying database contents");
    let stored = worker_verified_transactions::Entity::find()
        .all(&conn)
        .await
        .unwrap();
    
    assert_eq!(stored.len(), 1, "Should have exactly 1 record");
    let record = &stored[0];
    
    // Verify all fields
    assert_eq!(record.tx_hash, tx_hash, "Transaction hash should match");
    assert!(record.signature_valid, "Signature should be marked valid");
    assert_eq!(record.proof_verified, Some(true), "Proof should be marked verified");
    
    // Verify proof outputs stored as JSON
    let stored_proof_output: SpendPublic = serde_json::from_str(&record.proof_outputs)
        .expect("Should deserialize proof outputs");
    assert_eq!(stored_proof_output.anchor_root, anchor_root, "Stored anchor root should match");
    assert_eq!(stored_proof_output.nullifier, nullifier, "Stored nullifier should match");
    assert_eq!(stored_proof_output.withdraw_amount, withdraw_amount, "Stored amount should match");
    
    // Verify transaction data (without proof)
    assert!(record.transaction_data.contains("withdraw"), "Should contain withdraw call");
    assert!(record.transaction_data.contains("REMOVED"), "Proof should be removed from data");
    
    // Verify transaction state
    assert_eq!(
        record.transaction_state,
        worker_verified_transactions::TransactionState::Pending,
        "State should be Pending"
    );
    
    println!("  ✓ All database fields verified correctly!");
    
    // Step 9: Test idempotency - storing the same transaction again should update, not duplicate
    println!("\n✓ Step 9: Testing database upsert (idempotency)");
    let mut updated_proof_output = simulated_proof_output.clone();
    updated_proof_output.withdraw_amount = 999; // Change amount
    
    store_verified_midnight_transaction(
        &conn,
        &saver,
        &tx_hash,
        Some(&updated_proof_output),
        true,
        Some(true),
        &transaction_data,
        &tx_base64,
        None,  // No pre-auth data in test
        None,  // No encrypted notes in test
    )
    .await
    .expect("Should update existing record");
    
    let stored_after_update = worker_verified_transactions::Entity::find()
        .all(&conn)
        .await
        .unwrap();
    
    assert_eq!(stored_after_update.len(), 1, "Should still have exactly 1 record (not duplicated)");
    let updated_record = &stored_after_update[0];
    let updated_stored_proof: SpendPublic = serde_json::from_str(&updated_record.proof_outputs).unwrap();
    assert_eq!(updated_stored_proof.withdraw_amount, 999, "Amount should be updated");
    println!("  ✓ Upsert works correctly - no duplicates!");

    println!("\n=== ✓ ALL TESTS PASSED ===");
    println!("\nValidated:");
    println!("  ✓ Transaction creation and serialization");
    println!("  ✓ Signature verification");
    println!("  ✓ Transaction parsing");
    println!("  ✓ Proof verification (simulated)");
    println!("  ✓ Database storage");
    println!("  ✓ Database content verification");
    println!("  ✓ Database upsert/idempotency");
    println!();
}
