//! Generate a midnight deposit transaction
//! 
//! This deposits tokens into the shielded pool and creates a note commitment.

use anyhow::{Context, Result};
use borsh;
use demo_stf::runtime::{Runtime, RuntimeCall};
use midnight_privacy::{note_commitment, CallMessage, Hash32};
use rand;
use serde_json;
use sov_cli::wallet_state::PrivateKeyAndAddress;
use sov_demo_rollup::MockDemoRollup;
use sov_modules_api::execution_mode::Native;
use sov_modules_api::transaction::Transaction;
use sov_modules_api::{CryptoSpec, PrivateKey, Spec};
use sov_modules_rollup_blueprint::RollupBlueprint;
use sov_test_utils::default_test_signed_transaction;
use std::fs;
use std::path::PathBuf;

// Type alias matching the demo-rollup tests
type DemoRollupSpec = <MockDemoRollup<Native> as RollupBlueprint<Native>>::Spec;

// Import the actual CHAIN_HASH from demo-rollup's autogenerated.rs
mod demo_generated {
    include!("../../../examples/demo-rollup/autogenerated.rs");
}

const CHAIN_HASH: [u8; 32] = demo_generated::CHAIN_HASH;

fn main() -> Result<()> {
    println!("=== Midnight Deposit Transaction Generator ===\n");

    // Parse command line arguments
    let args: Vec<String> = std::env::args().collect();
    
    let output_file = if args.len() > 1 {
        PathBuf::from(&args[1])
    } else {
        PathBuf::from("midnight_deposit_tx.bin")
    };

    // Get parameters from environment or use test defaults
    let amount: u128 = std::env::var("DEPOSIT_AMOUNT")
        .unwrap_or_else(|_| "100".to_string())
        .parse()
        .context("Invalid DEPOSIT_AMOUNT")?;
    
    let nonce: u64 = std::env::var("NONCE")
        .unwrap_or_else(|_| "0".to_string())
        .parse()
        .context("Invalid NONCE")?;

    println!("Configuration:");
    println!("  Deposit amount: {}", amount);
    println!("  Nonce: {}\n", nonce);

    // Use fresh random parameters to avoid nullifier collisions
    let domain: Hash32 = [1u8; 32];  // Keep domain consistent
    let rho: Hash32 = rand::random();  // Random rho = unique nullifier
    let recipient: Hash32 = rand::random();  // Random recipient binding
    
    println!("Note parameters (for later withdrawal):");
    println!("  Domain: 0x{}", hex::encode(&domain[..8]));
    println!("  Rho: 0x{}", hex::encode(&rho[..8]));
    println!("  Recipient: 0x{}", hex::encode(&recipient[..8]));
    
    // Compute note commitment
    let cm = note_commitment(&domain, amount, &rho, &recipient);
    println!("  Commitment: 0x{}\n", hex::encode(cm));

    // Save note details for later withdrawal
    // Generate a fresh random nullifier key (SECRET!)
    let nf_key: Hash32 = rand::random();
    
    let note_details = serde_json::json!({
        "domain": hex::encode(domain),
        "amount": amount,
        "rho": hex::encode(rho),
        "recipient": hex::encode(recipient),
        "commitment": hex::encode(cm),
        "nf_key": hex::encode(nf_key)  // The secret key for nullifier derivation
    });
    
    let note_file = PathBuf::from("midnight_note_details.json");
    fs::write(&note_file, serde_json::to_string_pretty(&note_details)?)
        .context("Failed to write note details")?;
    println!("✓ Saved note details to: {}\n", note_file.display());

    // Load or generate private key
    let private_key = if let Ok(key_file) = std::env::var("PRIVATE_KEY_FILE") {
        println!("Loading private key from: {}", key_file);
        let key_data: PrivateKeyAndAddress<DemoRollupSpec> = 
            serde_json::from_str(&fs::read_to_string(&key_file)
                .context("Failed to read private key file")?)?;
        key_data.private_key
    } else {
        println!("⚠ No PRIVATE_KEY_FILE set, generating random key");
        <<DemoRollupSpec as Spec>::CryptoSpec as CryptoSpec>::PrivateKey::generate()
    };
    println!();

    // Build the deposit transaction
    println!("Building deposit transaction...");
    
    let msg = RuntimeCall::<DemoRollupSpec>::MidnightPrivacy(
        CallMessage::Deposit {
            amount,
            rho,
            recipient,
            gas: None,
        }
    );

    let tx: Transaction<Runtime<DemoRollupSpec>, DemoRollupSpec> = 
        default_test_signed_transaction(&private_key, &msg, nonce, &CHAIN_HASH);
    
    let tx_hash = tx.hash();
    println!("  ✓ Transaction hash: {}\n", tx_hash);

    // Serialize with borsh
    println!("Serializing transaction...");
    let tx_bytes = borsh::to_vec(&tx)
        .context("Failed to serialize transaction")?;
    
    println!("  ✓ Serialized size: {} bytes\n", tx_bytes.len());

    // Write to file
    fs::write(&output_file, &tx_bytes)
        .context("Failed to write transaction file")?;
    
    println!("✓ Wrote transaction to: {}\n", output_file.display());

    // Also output base64 encoding for direct API use
    use base64::Engine;
    let tx_base64 = base64::engine::general_purpose::STANDARD.encode(&tx_bytes);
    
    let json_payload = serde_json::json!({
        "body": tx_base64
    });
    
    let json_file = output_file.with_extension("json");
    fs::write(&json_file, serde_json::to_string_pretty(&json_payload)?)
        .context("Failed to write JSON payload")?;
    
    println!("✓ Wrote JSON payload to: {}\n", json_file.display());

    println!("=== Success! ===");
    println!("\nNext steps:");
    println!("1. Send this deposit transaction to the sequencer");
    println!("2. Wait for it to be confirmed");
    println!("3. Use the saved note details to generate a withdrawal proof");
    println!("\nNote details saved to: {}", note_file.display());

    Ok(())
}

