#!/usr/bin/env rust-script
//! Generate a midnight withdrawal transaction with a REAL Ligero proof
//! 
//! This creates a borsh-serialized transaction that can be sent to the
//! /midnight/verify-and-submit endpoint.

use anyhow::{Context, Result};
use borsh;
use demo_stf::runtime::{Runtime, RuntimeCall};
use midnight_privacy::{
    note_commitment, nullifier, root_from_path, CallMessage, Hash32, MerkleTree, SpendPublic,
};
use rand::Rng;
use sov_cli::wallet_state::PrivateKeyAndAddress;
use sov_demo_rollup::MockDemoRollup;
use sov_ligero_adapter::Ligero;
use sov_modules_api::execution_mode::Native;
use sov_modules_api::transaction::Transaction;
use sov_modules_api::{CryptoSpec, PrivateKey, Spec};
use sov_modules_rollup_blueprint::RollupBlueprint;
use sov_rollup_interface::zk::{Zkvm, ZkvmHost};
use sov_test_utils::default_test_signed_transaction;
use std::fs;
use std::path::PathBuf;
use std::time::Instant;

// Type alias matching the demo-rollup tests
type DemoRollupSpec = <MockDemoRollup<Native> as RollupBlueprint<Native>>::Spec;

// Import the actual CHAIN_HASH from demo-rollup's autogenerated.rs
mod demo_generated {
    include!("../../../examples/demo-rollup/autogenerated.rs");
}

const CHAIN_HASH: [u8; 32] = demo_generated::CHAIN_HASH;

fn main() -> Result<()> {
    println!("=== Midnight Withdrawal Transaction Generator (with REAL Ligero Proof) ===\n");

    // Parse command line arguments
    let args: Vec<String> = std::env::args().collect();
    
    let output_file = if args.len() > 1 {
        PathBuf::from(&args[1])
    } else {
        PathBuf::from("midnight_withdraw_tx.bin")
    };

    // Setup Ligero environment
    println!("Setting up Ligero environment...");
    let ligero_config = setup_ligero_env()?;
    println!("✓ Ligero binaries found");
    println!("  Prover: {}", ligero_config.prover_bin.display());
    println!("  Program: {}", ligero_config.program_path.display());
    println!("  Shader: {}", ligero_config.shader_path.display());
    println!();

    // Transaction parameters
    let tree_depth: u8 = std::env::var("TREE_DEPTH")
        .unwrap_or_else(|_| "16".to_string())
        .parse()
        .context("Invalid TREE_DEPTH")?;
    
    let note_value: u128 = std::env::var("NOTE_VALUE")
        .unwrap_or_else(|_| "1000".to_string())
        .parse()
        .context("Invalid NOTE_VALUE")?;
    
    let withdraw_amount: u128 = std::env::var("WITHDRAW_AMOUNT")
        .unwrap_or_else(|_| "500".to_string())
        .parse()
        .context("Invalid WITHDRAW_AMOUNT")?;
    
    if withdraw_amount > note_value {
        anyhow::bail!("Withdraw amount ({}) cannot exceed note value ({})", withdraw_amount, note_value);
    }
    
    let recipient_addr = std::env::var("RECIPIENT")
        .unwrap_or_else(|_| "sov1pv9skzctpv9skzctpv9skzctpv9skzctpv9skzctpv9skqm7ehv".to_string());
    
    let nonce: u64 = std::env::var("NONCE")
        .unwrap_or_else(|_| "0".to_string())
        .parse()
        .context("Invalid NONCE")?;

    println!("Configuration:");
    println!("  Tree depth: {}", tree_depth);
    println!("  Note value: {}", note_value);
    println!("  Withdraw amount: {}", withdraw_amount);
    println!("  Recipient: {}", recipient_addr);
    println!("  Nonce: {}\n", nonce);

    // Step 1: Create note and build Merkle tree
    println!("Step 1: Creating note and building Merkle tree...");
    
    let domain: Hash32 = [1u8; 32];
    let mut rng = rand::thread_rng();
    let rho: Hash32 = rng.gen();
    let note_recipient: Hash32 = rng.gen();
    let nf_key: Hash32 = rng.gen(); // SECRET nullifier key
    
    println!("  Note parameters:");
    println!("    Domain: 0x{}", hex::encode(&domain[..4]));
    println!("    Value: {}", note_value);
    println!("    Rho: 0x{}", hex::encode(&rho[..4]));
    println!("    Recipient: 0x{}", hex::encode(&note_recipient[..4]));
    
    // Compute note commitment
    let cm = note_commitment(&domain, note_value, &rho, &note_recipient);
    println!("  ✓ Note commitment: 0x{}", hex::encode(&cm[..8]));
    
    // Build Merkle tree
    let mut tree = MerkleTree::new(tree_depth);
    let position: u64 = 0;
    tree.set_leaf(position as usize, cm);
    let anchor = tree.root();
    println!("  ✓ Merkle root (anchor): 0x{}", hex::encode(&anchor[..8]));
    
    // Get authentication path
    let siblings = tree.open(position as usize);
    println!("  ✓ Authentication path: {} siblings", siblings.len());
    
    // Verify path locally
    let computed_root = root_from_path(&cm, position, &siblings, tree_depth);
    assert_eq!(computed_root, anchor, "Merkle path verification failed!");
    println!("  ✓ Path verified locally\n");
    
    // Derive nullifier
    let nf = nullifier(&domain, &nf_key, &rho);
    println!("  ✓ Nullifier: 0x{}\n", hex::encode(&nf[..8]));
    
    // Step 2: Generate REAL Ligero proof
    println!("Step 2: Generating REAL Ligero proof (this takes 30-60 seconds)...");
    
    let public_output = SpendPublic {
        anchor_root: anchor,
        nullifier: nf,
        withdraw_amount,
        output_commitments: vec![], // No change outputs in this simplified demo
    };
    
    let proof_start = Instant::now();
    let proof_bytes = generate_ligero_proof(
        &ligero_config,
        &domain,
        note_value,
        &rho,
        &note_recipient,
        &nf_key,
        position,
        tree_depth,
        &siblings,
        &anchor,
        &nf,
        withdraw_amount,
        &public_output,
    )?;
    let proof_time = proof_start.elapsed();
    
    println!("  ✓ Proof generated: {} bytes ({:.1}s)\n", proof_bytes.len(), proof_time.as_secs_f64());
    
    // Parse recipient address
    let recipient: <DemoRollupSpec as Spec>::Address = recipient_addr.parse()
        .context("Invalid recipient address")?;

    // Load or generate private key
    let private_key = if let Ok(key_file) = std::env::var("PRIVATE_KEY_FILE") {
        println!("Loading private key from: {}", key_file);
        let key_data: PrivateKeyAndAddress<DemoRollupSpec> = 
            serde_json::from_str(&fs::read_to_string(&key_file)
                .context("Failed to read private key file")?)?;
        key_data.private_key
    } else {
        println!("⚠ No PRIVATE_KEY_FILE set, generating random key");
        println!("  Set PRIVATE_KEY_FILE to use a specific key");
        println!("  Example: export PRIVATE_KEY_FILE=examples/test-data/keys/tx_signer_private_key.json");
        <<DemoRollupSpec as Spec>::CryptoSpec as CryptoSpec>::PrivateKey::generate()
    };
    println!();

    // Step 3: Build the transaction
    println!("Step 3: Building signed transaction...");
    
    let proof_safe_vec = proof_bytes.try_into()
        .map_err(|_| anyhow::anyhow!("Proof too large"))?;
    
    let msg = RuntimeCall::<DemoRollupSpec>::MidnightPrivacy(
        CallMessage::Withdraw {
            proof: proof_safe_vec,
            anchor_root: anchor,
            nullifier: nf,
            withdraw_amount,
            to: recipient,
            gas: None,
        }
    );

    let tx: Transaction<Runtime<DemoRollupSpec>, DemoRollupSpec> = 
        default_test_signed_transaction(&private_key, &msg, nonce, &CHAIN_HASH);
    
    let tx_hash = tx.hash();
    println!("  ✓ Transaction hash: {}\n", tx_hash);

    // Serialize with borsh
    println!("Step 4: Serializing transaction...");
    let tx_bytes = borsh::to_vec(&tx)
        .context("Failed to serialize transaction")?;
    
    println!("  ✓ Serialized size: {} bytes\n", tx_bytes.len());

    // Write to file
    fs::write(&output_file, &tx_bytes)
        .context("Failed to write transaction file")?;
    
    println!("✓ Wrote transaction to: {}\n", output_file.display());

    // Also output base64 encoding for direct API use
    use base64::Engine;
    let tx_base64 = base64::engine::general_purpose::STANDARD.encode(&tx_bytes);
    
    let json_payload = serde_json::json!({
        "body": tx_base64
    });
    
    let json_file = output_file.with_extension("json");
    fs::write(&json_file, serde_json::to_string_pretty(&json_payload)?)
        .context("Failed to write JSON payload")?;
    
    println!("✓ Wrote JSON payload to: {}\n", json_file.display());

    println!("=== Success! ===");
    println!("\nTransaction details:");
    println!("  Anchor root: 0x{}", hex::encode(anchor));
    println!("  Nullifier: 0x{}", hex::encode(nf));
    println!("  Withdraw amount: {}", withdraw_amount);
    println!("  Note value: {}", note_value);
    println!("  Change: {} (stays private)", note_value - withdraw_amount);
    println!("\nTo submit to the proof verifier service:");
    println!("  curl -X POST http://localhost:8080/midnight-privacy \\");
    println!("    -H 'Content-Type: application/json' \\");
    println!("    -d @{}\n", json_file.display());
    
    println!("Or use the helper script:");
    println!("  ./send_midnight_tx_simple.sh {}\n", output_file.display());

    Ok(())
}

#[derive(Debug)]
struct LigeroConfig {
    program_path: PathBuf,
    prover_bin: PathBuf,
    shader_path: PathBuf,
    packing: u32,
}

fn setup_ligero_env() -> Result<LigeroConfig> {
    // Auto-detect paths based on repository structure
    let repo_root = std::env::current_dir()?
        .ancestors()
        .find(|p| p.join("Cargo.toml").exists() && p.join("crates").exists())
        .ok_or_else(|| anyhow::anyhow!("Could not find repository root"))?
        .to_path_buf();

    let ligero_dir = repo_root.join("crates/adapters/ligero");

    // Detect OS
    let platform_dir = if cfg!(target_os = "macos") {
        "macos"
    } else if cfg!(target_os = "linux") {
        "linux-amd64"
    } else {
        anyhow::bail!("Unsupported platform. Supported: macOS, Linux");
    };

    let bin_dir = ligero_dir.join("bins").join(platform_dir).join("bin");
    let shader_dir = ligero_dir.join("bins").join(platform_dir).join("shader");

    let config = LigeroConfig {
        program_path: ligero_dir.join("guest/bins/programs/note_spend_guest.wasm"),
        prover_bin: bin_dir.join("webgpu_prover"),
        shader_path: shader_dir,
        packing: std::env::var("LIGERO_PACKING")
            .unwrap_or_else(|_| "8192".to_string())
            .parse()
            .context("Invalid LIGERO_PACKING")?,
    };

    // Validate files exist
    if !config.program_path.exists() {
        anyhow::bail!(
            "note_spend_guest.wasm not found at {}\nBuild it with: cd {} && ./build-guest-wasm.sh",
            config.program_path.display(),
            ligero_dir.join("guest").display()
        );
    }

    if !config.prover_bin.exists() {
        anyhow::bail!("webgpu_prover not found at {}", config.prover_bin.display());
    }

    if !config.shader_path.exists() {
        anyhow::bail!("Shader directory not found at {}", config.shader_path.display());
    }

    // Set environment variables for Ligero
    std::env::set_var("LIGERO_PROGRAM_PATH", &config.program_path);
    std::env::set_var("LIGERO_PROVER_BIN", &config.prover_bin);
    std::env::set_var("LIGERO_SHADER_PATH", &config.shader_path);
    std::env::set_var("LIGERO_PACKING", config.packing.to_string());

    Ok(config)
}

#[allow(clippy::too_many_arguments)]
fn generate_ligero_proof(
    config: &LigeroConfig,
    domain: &Hash32,
    value: u128,
    rho: &Hash32,
    recipient: &Hash32,
    nf_key: &Hash32,
    position: u64,
    tree_depth: u8,
    siblings: &[Hash32],
    anchor: &Hash32,
    nullifier: &Hash32,
    withdraw_amount: u128,
    public_output: &SpendPublic,
) -> Result<Vec<u8>> {
    let program_path = config.program_path.to_string_lossy().to_string();
    
    // Build private indices (1-based)
    // Arguments: domain(1), value(2), rho(3), recipient(4), nf_key(5), pos(6), depth(7), siblings(8..8+depth), anchor, nullifier, withdraw
    // Private: value, rho, recipient, nf_key, pos, and all siblings
    let mut private_indices = vec![
        2, // value
        3, // rho
        4, // recipient
        5, // nf_key
        6, // position
    ];
    
    // Add all sibling indices
    for i in 0..siblings.len() {
        private_indices.push(8 + i);
    }
    
    println!("  Private indices: {:?}", private_indices);
    
    let mut host = <Ligero as Zkvm>::Host::from_args(&program_path)
        .with_packing(config.packing)
        .with_private_indices(private_indices);
    
    // Add witness arguments
    host.add_hex_arg(hex::encode(domain)); // 1: PUBLIC
    host.add_str_arg(value.to_string()); // 2: PRIVATE (decimal u128)
    host.add_hex_arg(hex::encode(rho)); // 3: PRIVATE
    host.add_hex_arg(hex::encode(recipient)); // 4: PRIVATE
    host.add_hex_arg(hex::encode(nf_key)); // 5: PRIVATE
    host.add_str_arg(position.to_string()); // 6: PRIVATE (decimal u64)
    host.add_str_arg(tree_depth.to_string()); // 7: PUBLIC (decimal u32)
    
    // Add all siblings (PRIVATE)
    for sibling in siblings {
        host.add_hex_arg(hex::encode(sibling));
    }
    
    host.add_hex_arg(hex::encode(anchor)); // PUBLIC
    host.add_hex_arg(hex::encode(nullifier)); // PUBLIC
    host.add_str_arg(withdraw_amount.to_string()); // PUBLIC (decimal u128)
    
    // Set public output
    host.set_public_output(public_output)?;
    
    println!("  Calling webgpu_prover...");
    
    // Generate REAL proof
    let proof_data = host.run(true)
        .context("Failed to generate Ligero proof")?;
    
    Ok(proof_data)
}
