use anyhow::Result;
use borsh;
use hex;
use demo_stf::runtime::{Runtime, RuntimeCall};
use midnight_privacy::{note_commitment, nullifier, CallMessage, Hash32, SpendPublic, MerkleTree};
use rand::Rng;
use serde_json;
use sov_cli::wallet_state::PrivateKeyAndAddress;
use sov_rollup_ligero::MockDemoRollup;
use sov_ligero_adapter::Ligero;
use sov_modules_api::execution_mode::Native;
use sov_modules_api::transaction::Transaction;
use sov_modules_api::Spec;
use sov_modules_rollup_blueprint::RollupBlueprint;
use sov_rollup_interface::zk::{Zkvm, ZkvmHost};
use sov_test_utils::default_test_signed_transaction;
use std::fs;

type DemoRollupSpec = <MockDemoRollup<Native> as RollupBlueprint<Native>>::Spec;

mod demo_generated {
    include!("../../../examples/rollup-ligero/autogenerated.rs");
}

const CHAIN_HASH: [u8; 32] = demo_generated::CHAIN_HASH;

fn main() -> Result<()> {
    let domain: Hash32 = hex::decode(std::env::var("NOTE_DOMAIN")?)?
        .try_into().map_err(|_| anyhow::anyhow!("Invalid domain"))?;
    let value: u128 = std::env::var("NOTE_VALUE")?.parse()?;
    let rho: Hash32 = hex::decode(std::env::var("NOTE_RHO")?)?
        .try_into().map_err(|_| anyhow::anyhow!("Invalid rho"))?;
    let recipient: Hash32 = hex::decode(std::env::var("NOTE_RECIPIENT")?)?
        .try_into().map_err(|_| anyhow::anyhow!("Invalid recipient"))?;
    let nf_key: Hash32 = hex::decode(std::env::var("NOTE_NF_KEY")?)?
        .try_into().map_err(|_| anyhow::anyhow!("Invalid nf_key"))?;
    let out1_value: u128 = std::env::var("TRANSFER_OUT1")?.parse()?;
    let out2_value: u128 = std::env::var("TRANSFER_OUT2")?.parse()?;
    let position: u64 = std::env::var("NOTE_POSITION")?.parse()?;
    let nonce: u64 = std::env::var("NONCE")?.parse()?;
    
    let anchor_bytes: Vec<u8> = serde_json::from_str(&std::env::var("ANCHOR_ROOT")?)?;
    let anchor: Hash32 = anchor_bytes.try_into().map_err(|_| anyhow::anyhow!("Invalid anchor"))?;
    
    let cm = note_commitment(&domain, value, &rho, &recipient);
    let nf = nullifier(&domain, &nf_key, &rho);
    
    // Build tree with note at position
    let tree_depth: u8 = 16;
    let mut tree = MerkleTree::new(tree_depth);
    tree.set_leaf(position as usize, cm);
    let siblings = tree.open(position as usize);
    
    println!("Transfer: {} → {} + {}", value, out1_value, out2_value);
    println!("Input nullifier: 0x{}", hex::encode(&nf[..8]));
    
    // Create 2 output notes (pure shielded transfer, withdraw_amount = 0)
    let out1_rho: Hash32 = rand::thread_rng().gen();
    let out1_recipient: Hash32 = rand::thread_rng().gen();
    let cm_out1 = note_commitment(&domain, out1_value, &out1_rho, &out1_recipient);
    
    let out2_rho: Hash32 = rand::thread_rng().gen();
    let out2_recipient: Hash32 = rand::thread_rng().gen();
    let cm_out2 = note_commitment(&domain, out2_value, &out2_rho, &out2_recipient);
    
    // Save first output details for withdrawal step
    let out1_details = serde_json::json!({
        "domain": hex::encode(domain),
        "amount": out1_value,
        "rho": hex::encode(out1_rho),
        "recipient": hex::encode(out1_recipient),
        "nf_key": hex::encode(nf_key),
        "commitment": hex::encode(cm_out1)
    });
    fs::write("midnight_transfer_out1_details.json", serde_json::to_string_pretty(&out1_details)?)?;
    
    let public_output = SpendPublic {
        anchor_root: anchor,
        nullifier: nf,
        withdraw_amount: 0, // Pure shielded transfer
        output_commitments: vec![cm_out1, cm_out2],
        view_attestations: None,
    };
    
    let program_path = std::env::var("LIGERO_PROGRAM_PATH")?;
    let packing: u32 = std::env::var("LIGERO_PACKING")?.parse()?;
    
    let mut private_indices = vec![2, 3, 4, 5, 6];
    for i in 0..tree_depth as usize { private_indices.push(8 + i); }
    let base = 12 + tree_depth as usize;
    // Two outputs: mark all their fields as private
    for i in 0..6 { private_indices.push(base + i); }
    
    let mut host = <Ligero as Zkvm>::Host::from_args(&program_path)
        .with_packing(packing)
        .with_private_indices(private_indices);
    
    host.add_hex_arg(hex::encode(domain));
    host.add_str_arg(value.to_string());
    host.add_hex_arg(hex::encode(rho));
    host.add_hex_arg(hex::encode(recipient));
    host.add_hex_arg(hex::encode(nf_key));
    host.add_str_arg(position.to_string());
    host.add_str_arg(tree_depth.to_string());
    
    for sibling in &siblings {
        host.add_hex_arg(hex::encode(sibling));
    }
    
    host.add_hex_arg(hex::encode(anchor));
    host.add_hex_arg(hex::encode(nf));
    host.add_str_arg("0".to_string());  // withdraw_amount = 0
    host.add_str_arg("2".to_string());  // n_out = 2
    
    // Output 1
    host.add_str_arg(out1_value.to_string());
    host.add_hex_arg(hex::encode(out1_rho));
    host.add_hex_arg(hex::encode(out1_recipient));
    host.add_hex_arg(hex::encode(cm_out1));
    
    // Output 2
    host.add_str_arg(out2_value.to_string());
    host.add_hex_arg(hex::encode(out2_rho));
    host.add_hex_arg(hex::encode(out2_recipient));
    host.add_hex_arg(hex::encode(cm_out2));
    
    host.set_public_output(&public_output)?;
    
    println!("Generating proof...");
    let proof_bytes = host.run(true)?;
    println!("✓ Proof generated: {} bytes", proof_bytes.len());
    
    let key_data: PrivateKeyAndAddress<DemoRollupSpec> =
        serde_json::from_str(&fs::read_to_string(std::env::var("PRIVATE_KEY_FILE")?)?)?;
    
    let proof_safe = proof_bytes.try_into()
        .map_err(|_| anyhow::anyhow!("Proof too large"))?;
    
    let msg = RuntimeCall::<DemoRollupSpec>::MidnightPrivacy(CallMessage::Transfer {
        proof: proof_safe,
        anchor_root: anchor,
        nullifier: nf,
        view_ciphertexts: None,
        gas: None,
    });
    
    let tx: Transaction<Runtime<DemoRollupSpec>, DemoRollupSpec> = 
        default_test_signed_transaction(&key_data.private_key, &msg, nonce, &CHAIN_HASH);
    
    let tx_bytes = borsh::to_vec(&tx)?;
    fs::write("midnight_transfer_tx.bin", &tx_bytes)?;
    
    let tx_base64 = base64::Engine::encode(&base64::engine::general_purpose::STANDARD, &tx_bytes);
    let tx_json = serde_json::json!({"body": tx_base64});
    
    fs::write("midnight_transfer_tx.json", serde_json::to_string_pretty(&tx_json)?)?;
    
    println!("✓ Transaction ready: midnight_transfer_tx.json");
    Ok(())
}
