use anyhow::{Context, Result};
use borsh;
use demo_stf::runtime::{Runtime, RuntimeCall};
use hex;
use midnight_privacy::{
    nf_key_from_sk, note_commitment, nullifier, pk_from_sk, recipient_from_pk, recipient_from_sk,
    CallMessage, Hash32, MerkleTree, SpendPublic,
};
use rand::Rng;
use serde_json;
use sov_cli::wallet_state::PrivateKeyAndAddress;
use sov_ligero_adapter::Ligero;
use sov_modules_api::execution_mode::Native;
use sov_modules_api::transaction::Transaction;
use sov_modules_rollup_blueprint::RollupBlueprint;
use sov_rollup_interface::zk::{Zkvm, ZkvmHost};
use sov_rollup_ligero::MockDemoRollup;
use sov_test_utils::default_test_signed_transaction;
use std::fs;
use serde::Deserialize;

type DemoRollupSpec = <MockDemoRollup<Native> as RollupBlueprint<Native>>::Spec;

mod demo_generated {
    include!("../../../examples/rollup-ligero/autogenerated.rs");
}

const CHAIN_HASH: [u8; 32] = demo_generated::CHAIN_HASH;

#[derive(Deserialize)]
struct NotesResponse {
    notes: Vec<NoteEntry>,
    current_root: Option<Vec<u8>>,
}

#[derive(Deserialize)]
struct NoteEntry {
    position: u64,
    commitment: Vec<u8>,
}

fn decode_hash32_env(var: &str) -> Result<Hash32> {
    let raw = std::env::var(var).with_context(|| format!("Missing env var {var}"))?;
    let raw = raw.trim();
    let raw = raw.strip_prefix("0x").unwrap_or(raw);
    hex::decode(raw)
        .with_context(|| format!("Invalid hex in env var {var}"))?
        .try_into()
        .map_err(|_| anyhow::anyhow!("Invalid {var} length (expected 32 bytes)"))
}

fn load_notes_from_source() -> Option<NotesResponse> {
    if let Ok(path) = std::env::var("NOTES_FILE") {
        let data = fs::read_to_string(path).ok()?;
        return serde_json::from_str(&data).ok();
    }

    if let Ok(node_url) = std::env::var("NODE_API_URL") {
        let url = format!("{}/modules/midnight-privacy/notes?limit=200&reverse=true", node_url);
        if let Ok(resp) = reqwest::blocking::get(url) {
            return resp.json::<NotesResponse>().ok();
        }
    }
    None
}

fn main() -> Result<()> {
    let domain: Hash32 = decode_hash32_env("NOTE_DOMAIN")?;
    let value: u128 = std::env::var("NOTE_VALUE")
        .with_context(|| "Missing env var NOTE_VALUE")?
        .parse()
        .context("Invalid NOTE_VALUE")?;
    let rho: Hash32 = decode_hash32_env("NOTE_RHO")?;
    let spend_sk: Hash32 = decode_hash32_env("NOTE_SPEND_SK")?;
    let out1_value: u128 = std::env::var("TRANSFER_OUT1")?.parse()?;
    let out2_value: u128 = std::env::var("TRANSFER_OUT2")?.parse()?;
    let position: u64 = std::env::var("NOTE_POSITION")?.parse()?;
    let nonce: u64 = std::env::var("NONCE")?.parse()?;
    anyhow::ensure!(
        out1_value + out2_value == value,
        "Transfer outputs must sum to input value: in={} out1={} out2={}",
        value,
        out1_value,
        out2_value
    );

    let anchor_bytes: Vec<u8> = serde_json::from_str(&std::env::var("ANCHOR_ROOT")?)?;
    let mut anchor: Hash32 = anchor_bytes
        .try_into()
        .map_err(|_| anyhow::anyhow!("Invalid anchor"))?;

    let in_recipient = recipient_from_sk(&domain, &spend_sk);
    let cm = note_commitment(&domain, value, &rho, &in_recipient);
    let nf_key = nf_key_from_sk(&domain, &spend_sk);
    let nf = nullifier(&domain, &nf_key, &rho);

    // Build tree with on-chain notes when available; otherwise fall back to single-leaf tree.
    let tree_depth: u8 = 16;
    let mut tree = MerkleTree::new(tree_depth);
    if let Some(notes_resp) = load_notes_from_source() {
        for note in notes_resp.notes {
            if note.position >= (1u64 << tree_depth) {
                continue;
            }
            if let Ok(commitment) = note.commitment.clone().try_into() {
                tree.set_leaf(note.position as usize, commitment);
            }
        }
        // Ensure our note is present (in case not returned due to limit/filter).
        tree.set_leaf(position as usize, cm);
        let computed_root: Hash32 = tree
            .root()
            .try_into()
            .map_err(|_| anyhow::anyhow!("Computed root has invalid length"))?;
        if computed_root != anchor {
            println!(
                "ℹ️  Recomputed anchor from notes differs from provided anchor; using computed root"
            );
            anchor = computed_root;
        }
    } else {
        tree.set_leaf(position as usize, cm);
    }
    let siblings = tree.open(position as usize);

    println!("Transfer: {} → {} + {}", value, out1_value, out2_value);
    println!("Input nullifier: 0x{}", hex::encode(&nf[..8]));

    // Create 2 output notes (pure shielded transfer, withdraw_amount = 0)
    let out1_rho: Hash32 = rand::thread_rng().gen();
    let out1_spend_sk: Hash32 = rand::thread_rng().gen();
    let out1_pk: Hash32 = pk_from_sk(&out1_spend_sk);
    let out1_recipient: Hash32 = recipient_from_pk(&domain, &out1_pk);
    let cm_out1 = note_commitment(&domain, out1_value, &out1_rho, &out1_recipient);

    let out2_rho: Hash32 = rand::thread_rng().gen();
    let out2_spend_sk: Hash32 = rand::thread_rng().gen();
    let out2_pk: Hash32 = pk_from_sk(&out2_spend_sk);
    let out2_recipient: Hash32 = recipient_from_pk(&domain, &out2_pk);
    let cm_out2 = note_commitment(&domain, out2_value, &out2_rho, &out2_recipient);

    // Save first output details for withdrawal step
    let out1_details = serde_json::json!({
        "domain": hex::encode(domain),
        "amount": out1_value,
        "rho": hex::encode(out1_rho),
        "recipient": hex::encode(out1_recipient),
        "commitment": hex::encode(cm_out1),
        "spend_sk": hex::encode(out1_spend_sk),
        "nf_key": hex::encode(nf_key_from_sk(&domain, &out1_spend_sk)) // derived (debug)
    });
    fs::write(
        "midnight_transfer_out1_details.json",
        serde_json::to_string_pretty(&out1_details)?,
    )?;

    let public_output = SpendPublic {
        anchor_root: anchor,
        nullifier: nf,
        withdraw_amount: 0, // Pure shielded transfer
        output_commitments: vec![cm_out1, cm_out2],
        view_attestations: None,
    };

    let program_path = std::env::var("LIGERO_PROGRAM_PATH")?;
    let packing: u32 = std::env::var("LIGERO_PACKING")
        .unwrap_or_else(|_| "8192".to_string())
        .parse()
        .context("Invalid LIGERO_PACKING")?;

    // note_spend_guest ABI:
    // 1 domain (public)
    // 2 value (public)
    // 3 rho (private)
    // 4 recipient (private, layout only)
    // 5 spend_sk (private)
    // 6 depth (public)
    // 7..7+depth-1 position bits (private)
    // 7+depth..7+2*depth-1 siblings (private)
    // ...
    let depth_usize = tree_depth as usize;
    let n_out: usize = 2;
    let mut private_indices = vec![3, 4, 5];
    for j in 0..depth_usize {
        private_indices.push(7 + j);
    }
    for j in 0..depth_usize {
        private_indices.push(7 + depth_usize + j);
    }
    for out_idx in 0..n_out {
        let out_base = 11 + 2 * depth_usize + 4 * out_idx;
        private_indices.extend_from_slice(&[out_base + 1, out_base + 2]); // out_rho, out_pk
    }

    let mut host = <Ligero as Zkvm>::Host::from_args(&program_path)
        .with_packing(packing)
        .with_private_indices(private_indices);

    // Typed binary ABI for zkVM performance
    host.add_hex_arg(hex::encode(domain));
    host.add_u64_arg(u64::try_from(value).context("NOTE_VALUE too large")?);
    host.add_hex_arg(hex::encode(rho));
    host.add_hex_arg(hex::encode(in_recipient));
    host.add_hex_arg(hex::encode(spend_sk));
    host.add_u64_arg(tree_depth as u64);

    // position bits (field elements 0/1 as 32-byte BE)
    for lvl in 0..depth_usize {
        let bit = ((position >> lvl) & 1) as u8;
        let mut bit_bytes = [0u8; 32];
        bit_bytes[31] = bit;
        host.add_hex_arg(hex::encode(bit_bytes));
    }

    for sibling in &siblings {
        host.add_hex_arg(hex::encode(sibling));
    }

    host.add_str_arg(format!("0x{}", hex::encode(anchor)));
    host.add_str_arg(format!("0x{}", hex::encode(nf)));
    host.add_u64_arg(0); // withdraw_amount = 0
    host.add_u64_arg(n_out as u64);

    // Output 1
    host.add_u64_arg(u64::try_from(out1_value).context("TRANSFER_OUT1 too large")?);
    host.add_hex_arg(hex::encode(out1_rho));
    host.add_hex_arg(hex::encode(out1_pk));
    host.add_hex_arg(hex::encode(cm_out1));

    // Output 2
    host.add_u64_arg(u64::try_from(out2_value).context("TRANSFER_OUT2 too large")?);
    host.add_hex_arg(hex::encode(out2_rho));
    host.add_hex_arg(hex::encode(out2_pk));
    host.add_hex_arg(hex::encode(cm_out2));

    host.set_public_output(&public_output)?;

    println!("Generating proof...");
    let proof_bytes = host
        .run(true)
        .context("Ligero prover did not produce a valid proof")?;
    println!("✓ Proof generated: {} bytes", proof_bytes.len());

    let key_data: PrivateKeyAndAddress<DemoRollupSpec> =
        serde_json::from_str(&fs::read_to_string(std::env::var("PRIVATE_KEY_FILE")?)?)?;

    let proof_safe = proof_bytes
        .try_into()
        .map_err(|_| anyhow::anyhow!("Proof too large"))?;

    let msg = RuntimeCall::<DemoRollupSpec>::MidnightPrivacy(CallMessage::Transfer {
        proof: proof_safe,
        anchor_root: anchor,
        nullifier: nf,
        gas: None,
        view_ciphertexts: None,
    });

    let tx: Transaction<Runtime<DemoRollupSpec>, DemoRollupSpec> =
        default_test_signed_transaction(&key_data.private_key, &msg, nonce, &CHAIN_HASH);

    let tx_bytes = borsh::to_vec(&tx)?;
    fs::write("midnight_transfer_tx.bin", &tx_bytes)?;

    let tx_base64 = base64::Engine::encode(&base64::engine::general_purpose::STANDARD, &tx_bytes);
    let tx_json = serde_json::json!({"body": tx_base64});

    fs::write(
        "midnight_transfer_tx.json",
        serde_json::to_string_pretty(&tx_json)?,
    )?;

    println!("✓ Transaction ready: midnight_transfer_tx.json");
    Ok(())
}
