use anyhow::{Context, Result};
use borsh;
use demo_stf::runtime::{Runtime, RuntimeCall};
use hex;
use midnight_privacy::{
    nf_key_from_sk, note_commitment, nullifier, pk_from_sk, recipient_from_pk, recipient_from_sk,
    CallMessage, Hash32, MerkleTree, SpendPublic,
};
use rand::Rng;
use serde_json;
use sov_cli::wallet_state::PrivateKeyAndAddress;
use sov_ligero_adapter::Ligero;
use sov_modules_api::execution_mode::Native;
use sov_modules_api::transaction::Transaction;
use sov_modules_rollup_blueprint::RollupBlueprint;
use sov_rollup_interface::zk::{Zkvm, ZkvmHost};
use sov_rollup_ligero::MockDemoRollup;
use sov_test_utils::default_test_signed_transaction;
use std::fs;
use serde::Deserialize;

type DemoRollupSpec = <MockDemoRollup<Native> as RollupBlueprint<Native>>::Spec;

mod demo_generated {
    include!("../../../examples/rollup-ligero/autogenerated.rs");
}

const CHAIN_HASH: [u8; 32] = demo_generated::CHAIN_HASH;

#[derive(Deserialize)]
struct NotesResponse {
    notes: Vec<NoteEntry>,
    #[serde(default)]
    current_root: Option<Vec<u8>>,
}

#[derive(Deserialize)]
struct NoteEntry {
    position: u64,
    commitment: Vec<u8>,
}

fn decode_hash32_env(var: &str) -> Result<Hash32> {
    let raw = std::env::var(var).with_context(|| format!("Missing env var {var}"))?;
    let raw = raw.trim();
    let raw = raw.strip_prefix("0x").unwrap_or(raw);
    hex::decode(raw)
        .with_context(|| format!("Invalid hex in env var {var}"))?
        .try_into()
        .map_err(|_| anyhow::anyhow!("Invalid {var} length (expected 32 bytes)"))
}

fn load_notes_from_source() -> Option<NotesResponse> {
    if let Ok(path) = std::env::var("NOTES_FILE") {
        let data = fs::read_to_string(path).ok()?;
        return serde_json::from_str(&data).ok();
    }

    if let Ok(node_url) = std::env::var("NODE_API_URL") {
        // IMPORTANT: fetch ALL notes (pagination) so the Merkle root/path matches on-chain state.
        let mut all_notes: Vec<NoteEntry> = Vec::new();
        let mut offset: usize = 0;
        let limit: usize = 1000;
        let mut last_root: Option<Vec<u8>> = None;

        loop {
            let url = format!(
                "{}/modules/midnight-privacy/notes?limit={}&offset={}",
                node_url, limit, offset
            );
            let resp = reqwest::blocking::get(&url).ok()?;
            let page = resp.json::<NotesResponse>().ok()?;

            if let Some(root) = page.current_root.clone() {
                last_root = Some(root);
            }

            let n = page.notes.len();
            all_notes.extend(page.notes);
            if n < limit {
                break;
            }
            offset += n;
        }

        return Some(NotesResponse {
            notes: all_notes,
            current_root: last_root,
        });
    }
    None
}

fn main() -> Result<()> {
    let domain: Hash32 = decode_hash32_env("OUT1_DOMAIN")?;
    let value: u128 = std::env::var("OUT1_VALUE")
        .with_context(|| "Missing env var OUT1_VALUE")?
        .parse()
        .context("Invalid OUT1_VALUE")?;
    let rho: Hash32 = decode_hash32_env("OUT1_RHO")?;
    let spend_sk: Hash32 = decode_hash32_env("OUT1_SPEND_SK")?;
    let withdraw_amount: u128 = std::env::var("WITHDRAW_AMOUNT")
        .with_context(|| "Missing env var WITHDRAW_AMOUNT")?
        .parse()
        .context("Invalid WITHDRAW_AMOUNT")?;
    let position: u64 = std::env::var("OUT1_POSITION")?.parse()?;
    let nonce: u64 = std::env::var("NONCE")?.parse()?;
    let recipient_addr: String = std::env::var("RECIPIENT")?;
    anyhow::ensure!(
        withdraw_amount <= value,
        "WITHDRAW_AMOUNT exceeds note value: withdraw={} value={}",
        withdraw_amount,
        value
    );

    let anchor_bytes: Vec<u8> = serde_json::from_str(&std::env::var("TRANSFER_ROOT")?)?;
    let mut anchor: Hash32 = anchor_bytes
        .try_into()
        .map_err(|_| anyhow::anyhow!("Invalid anchor"))?;

    let in_recipient = recipient_from_sk(&domain, &spend_sk);
    let cm = note_commitment(&domain, value, &rho, &in_recipient);
    let nf_key = nf_key_from_sk(&domain, &spend_sk);
    let nf = nullifier(&domain, &nf_key, &rho);

    // Build tree from on-chain notes when available; otherwise fall back to single-leaf tree.
    let tree_depth: u8 = 16;
    let mut tree = MerkleTree::new(tree_depth);
    if let Some(notes_resp) = load_notes_from_source() {
        // Prefer the fresh root reported by the node (avoid stale TRANSFER_ROOT from earlier script steps).
        if let Some(root) = notes_resp.current_root.clone() {
            if let Ok(root32) = <[u8; 32]>::try_from(root) {
                let fresh: Hash32 = root32;
                if fresh != anchor {
                    println!(
                        "ℹ️  Provided TRANSFER_ROOT differs from node current_root; using node root"
                    );
                }
                anchor = fresh;
            }
        }
        for note in notes_resp.notes {
            if note.position >= (1u64 << tree_depth) {
                continue;
            }
            if let Ok(commitment) = note.commitment.clone().try_into() {
                tree.set_leaf(note.position as usize, commitment);
            }
        }
        // Ensure our note is present (in case not returned due to limit/filter)
        tree.set_leaf(position as usize, cm);

        let computed_root: Hash32 = tree
            .root()
            .try_into()
            .map_err(|_| anyhow::anyhow!("Computed root has invalid length"))?;
        anyhow::ensure!(
            computed_root == anchor,
            "Anchor root mismatch: env/node anchor = 0x{}, but Merkle root computed from on-chain notes = 0x{}. \
             This usually means your note isn't fully indexed yet, or the note list is incomplete.",
            hex::encode(anchor),
            hex::encode(computed_root),
        );
    } else {
        tree.set_leaf(position as usize, cm);
    }
    let siblings = tree.open(position as usize);

    println!(
        "Withdraw: {} → {} (transparent) + {} (change)",
        value,
        withdraw_amount,
        value - withdraw_amount
    );
    println!("Input nullifier: 0x{}", hex::encode(&nf[..8]));

    // Change output (if any)
    let change_value = value - withdraw_amount;
    let (n_out, cm_change, change_rho, change_pk) = if change_value > 0 {
        let change_rho: Hash32 = rand::thread_rng().gen();
        // Keep change owned by the same spend key.
        let change_pk: Hash32 = pk_from_sk(&spend_sk);
        let change_recipient: Hash32 = recipient_from_pk(&domain, &change_pk);
        let cm_change = note_commitment(&domain, change_value, &change_rho, &change_recipient);
        (1usize, Some(cm_change), Some(change_rho), Some(change_pk))
    } else {
        (0usize, None, None, None)
    };

    let public_output = SpendPublic {
        anchor_root: anchor,
        nullifier: nf,
        withdraw_amount,
        output_commitments: cm_change.into_iter().collect(),
        view_attestations: None,
    };

    let program_path = std::env::var("LIGERO_PROGRAM_PATH")?;
    let packing: u32 = std::env::var("LIGERO_PACKING")
        .unwrap_or_else(|_| "8192".to_string())
        .parse()
        .context("Invalid LIGERO_PACKING")?;

    let depth_usize = tree_depth as usize;
    let mut private_indices = vec![3, 4, 5]; // rho, recipient (layout), spend_sk
    // position bits
    for j in 0..depth_usize {
        private_indices.push(7 + j);
    }
    // siblings
    for j in 0..depth_usize {
        private_indices.push(7 + depth_usize + j);
    }
    // output 0: out_rho, out_pk private
    if n_out == 1 {
        let out_base = 11 + 2 * depth_usize;
        private_indices.extend_from_slice(&[out_base + 1, out_base + 2]);
    }

    let mut host = <Ligero as Zkvm>::Host::from_args(&program_path)
        .with_packing(packing)
        .with_private_indices(private_indices);

    // Typed binary ABI for zkVM performance
    host.add_hex_arg(hex::encode(domain));
    host.add_u64_arg(u64::try_from(value).context("OUT1_VALUE too large")?);
    host.add_hex_arg(hex::encode(rho));
    host.add_hex_arg(hex::encode(in_recipient));
    host.add_hex_arg(hex::encode(spend_sk));
    host.add_u64_arg(tree_depth as u64);

    // position bits (field elements 0/1 as 32-byte BE)
    for lvl in 0..depth_usize {
        let bit = ((position >> lvl) & 1) as u8;
        let mut bit_bytes = [0u8; 32];
        bit_bytes[31] = bit;
        host.add_hex_arg(hex::encode(bit_bytes));
    }

    for sibling in &siblings {
        host.add_hex_arg(hex::encode(sibling));
    }

    host.add_str_arg(format!("0x{}", hex::encode(anchor)));
    host.add_str_arg(format!("0x{}", hex::encode(nf)));
    host.add_u64_arg(u64::try_from(withdraw_amount).context("WITHDRAW_AMOUNT too large")?);
    host.add_u64_arg(n_out as u64);

    if n_out == 1 {
        let cm_change = cm_change.expect("cm_change missing for change output");
        let change_rho = change_rho.expect("change_rho missing for change output");
        let change_pk = change_pk.expect("change_pk missing for change output");
        host.add_u64_arg(u64::try_from(change_value).context("Change value too large")?);
        host.add_hex_arg(hex::encode(change_rho));
        host.add_hex_arg(hex::encode(change_pk));
        host.add_hex_arg(hex::encode(cm_change));
    }

    host.set_public_output(&public_output)?;

    println!("Generating proof...");
    let proof_bytes = host
        .run(true)
        .context("Ligero prover did not produce a valid proof")?;
    println!("✓ Proof generated: {} bytes", proof_bytes.len());

    let key_data: PrivateKeyAndAddress<DemoRollupSpec> =
        serde_json::from_str(&fs::read_to_string(std::env::var("PRIVATE_KEY_FILE")?)?)?;

    let proof_safe = proof_bytes
        .try_into()
        .map_err(|_| anyhow::anyhow!("Proof too large"))?;

    let recipient_parsed = recipient_addr
        .parse()
        .map_err(|e| anyhow::anyhow!("Invalid recipient address: {}", e))?;

    let msg = RuntimeCall::<DemoRollupSpec>::MidnightPrivacy(CallMessage::Withdraw {
        proof: proof_safe,
        anchor_root: anchor,
        nullifier: nf,
        withdraw_amount,
        to: recipient_parsed,
        view_ciphertexts: None,
        gas: None,
    });

    let tx: Transaction<Runtime<DemoRollupSpec>, DemoRollupSpec> =
        default_test_signed_transaction(&key_data.private_key, &msg, nonce, &CHAIN_HASH);

    let tx_bytes = borsh::to_vec(&tx)?;
    fs::write("midnight_withdraw_tx.bin", &tx_bytes)?;

    let tx_base64 = base64::Engine::encode(&base64::engine::general_purpose::STANDARD, &tx_bytes);
    let tx_json = serde_json::json!({"body": tx_base64});

    fs::write(
        "midnight_withdraw_tx.json",
        serde_json::to_string_pretty(&tx_json)?,
    )?;

    println!("✓ Transaction ready: midnight_withdraw_tx.json");
    Ok(())
}
