use anyhow::{Context, Result};
use borsh;
use demo_stf::runtime::{Runtime, RuntimeCall};
use hex;
use midnight_privacy::{
    note_commitment, nullifier, pk_from_sk, pk_ivk_from_sk, recipient_from_pk_v2, CallMessage,
    Hash32, MerkleTree, PrivacyAddress, SpendPublic,
};
use rand::Rng;
use serde_json;
use sov_cli::wallet_state::PrivateKeyAndAddress;
use sov_ligero_adapter::Ligero;
use sov_modules_api::execution_mode::Native;
use sov_modules_api::transaction::Transaction;
use sov_modules_rollup_blueprint::RollupBlueprint;
use sov_rollup_interface::zk::{Zkvm, ZkvmHost};
use sov_rollup_ligero::MockDemoRollup;
use sov_test_utils::default_test_signed_transaction;
use sov_modules_api::Spec;
use std::fs;
use serde::Deserialize;

mod note_spend_guest_v2;

type DemoRollupSpec = <MockDemoRollup<Native> as RollupBlueprint<Native>>::Spec;

mod demo_generated {
    include!("../../../examples/rollup-ligero/autogenerated.rs");
}

const CHAIN_HASH: [u8; 32] = demo_generated::CHAIN_HASH;

#[derive(Deserialize)]
struct NotesResponse {
    notes: Vec<NoteEntry>,
    #[serde(default)]
    current_root: Option<Vec<u8>>,
}

#[derive(Deserialize)]
struct NoteEntry {
    position: u64,
    commitment: Vec<u8>,
}

fn decode_hash32_env(var: &str) -> Result<Hash32> {
    let raw = std::env::var(var).with_context(|| format!("Missing env var {var}"))?;
    let raw = raw.trim();
    let raw = raw.strip_prefix("0x").unwrap_or(raw);
    hex::decode(raw)
        .with_context(|| format!("Invalid hex in env var {var}"))?
        .try_into()
        .map_err(|_| anyhow::anyhow!("Invalid {var} length (expected 32 bytes)"))
}

fn decode_hash32_str(label: &str, raw: &str) -> Result<Hash32> {
    let raw = raw.trim();
    let raw = raw.strip_prefix("0x").unwrap_or(raw);
    hex::decode(raw)
        .with_context(|| format!("Invalid hex in {label}"))?
        .try_into()
        .map_err(|_| anyhow::anyhow!("Invalid {label} length (expected 32 bytes)"))
}

fn load_notes_from_source() -> Option<NotesResponse> {
    if let Ok(path) = std::env::var("NOTES_FILE") {
        let data = fs::read_to_string(path).ok()?;
        return serde_json::from_str(&data).ok();
    }

    if let Ok(node_url) = std::env::var("NODE_API_URL") {
        // IMPORTANT: fetch ALL notes (pagination) so the Merkle root/path matches on-chain state.
        let mut all_notes: Vec<NoteEntry> = Vec::new();
        let mut offset: usize = 0;
        let limit: usize = 1000;
        let mut last_root: Option<Vec<u8>> = None;

        loop {
            let url = format!(
                "{}/modules/midnight-privacy/notes?limit={}&offset={}",
                node_url, limit, offset
            );
            let resp = reqwest::blocking::get(&url).ok()?;
            let page = resp.json::<NotesResponse>().ok()?;

            if let Some(root) = page.current_root.clone() {
                last_root = Some(root);
            }

            let n = page.notes.len();
            all_notes.extend(page.notes);
            if n < limit {
                break;
            }
            offset += n;
        }

        return Some(NotesResponse {
            notes: all_notes,
            current_root: last_root,
        });
    }
    None
}

fn main() -> Result<()> {
    let domain: Hash32 = decode_hash32_env("OUT1_DOMAIN")?;
    let value: u128 = std::env::var("OUT1_VALUE")
        .with_context(|| "Missing env var OUT1_VALUE")?
        .parse()
        .context("Invalid OUT1_VALUE")?;
    let rho: Hash32 = decode_hash32_env("OUT1_RHO")?;
    let spend_sk: Hash32 = decode_hash32_env("OUT1_SPEND_SK")?;
    let withdraw_amount: u128 = std::env::var("WITHDRAW_AMOUNT")
        .with_context(|| "Missing env var WITHDRAW_AMOUNT")?
        .parse()
        .context("Invalid WITHDRAW_AMOUNT")?;
    let position: u64 = std::env::var("OUT1_POSITION")?.parse()?;
    let nonce: u64 = std::env::var("NONCE")?.parse()?;
    let recipient_addr: String = std::env::var("RECIPIENT")?;
    let to_addr: <DemoRollupSpec as Spec>::Address = recipient_addr
        .parse()
        .context("Invalid RECIPIENT address")?;
    anyhow::ensure!(
        withdraw_amount <= value,
        "WITHDRAW_AMOUNT exceeds note value: withdraw={} value={}",
        withdraw_amount,
        value
    );

    let anchor_bytes: Vec<u8> = serde_json::from_str(&std::env::var("TRANSFER_ROOT")?)?;
    let mut anchor: Hash32 = anchor_bytes
        .try_into()
        .map_err(|_| anyhow::anyhow!("Invalid anchor"))?;

    let pk_spend_owner = pk_from_sk(&spend_sk);
    let pk_ivk_owner = pk_ivk_from_sk(&domain, &spend_sk);
    let in_recipient = recipient_from_pk_v2(&domain, &pk_spend_owner, &pk_ivk_owner);
    let in_sender_id: Hash32 = match std::env::var("OUT1_SENDER_ID").ok() {
        Some(v) => decode_hash32_str("OUT1_SENDER_ID", &v)?,
        None => in_recipient, // deposit-created notes use sender_id = recipient
    };
    let value_u64 = u64::try_from(value).context("OUT1_VALUE too large")?;
    let cm = note_commitment(&domain, value_u64, &rho, &in_recipient, &in_sender_id);
    let nf_key = midnight_privacy::nf_key_from_sk(&domain, &spend_sk);
    let nf = nullifier(&domain, &nf_key, &rho);

    // Build tree from on-chain notes when available; otherwise fall back to single-leaf tree.
    let tree_depth: u8 = 16;
    let mut tree = MerkleTree::new(tree_depth);
    if let Some(notes_resp) = load_notes_from_source() {
        // Prefer the fresh root reported by the node (avoid stale TRANSFER_ROOT from earlier script steps).
        if let Some(root) = notes_resp.current_root.clone() {
            if let Ok(root32) = <[u8; 32]>::try_from(root) {
                let fresh: Hash32 = root32;
                if fresh != anchor {
                    println!(
                        "ℹ️  Provided TRANSFER_ROOT differs from node current_root; using node root"
                    );
                }
                anchor = fresh;
            }
        }
        for note in notes_resp.notes {
            if note.position >= (1u64 << tree_depth) {
                continue;
            }
            if let Ok(commitment) = note.commitment.clone().try_into() {
                tree.set_leaf(note.position as usize, commitment);
            }
        }
        // Ensure our note is present (in case not returned due to limit/filter)
        tree.set_leaf(position as usize, cm);

        let computed_root: Hash32 = tree
            .root()
            .try_into()
            .map_err(|_| anyhow::anyhow!("Computed root has invalid length"))?;
        anyhow::ensure!(
            computed_root == anchor,
            "Anchor root mismatch: env/node anchor = 0x{}, but Merkle root computed from on-chain notes = 0x{}. \
             This usually means your note isn't fully indexed yet, or the note list is incomplete.",
            hex::encode(anchor),
            hex::encode(computed_root),
        );
    } else {
        tree.set_leaf(position as usize, cm);
    }
    let siblings = tree.open(position as usize);

    println!(
        "Withdraw: {} → {} (transparent) + {} (change)",
        value,
        withdraw_amount,
        value - withdraw_amount
    );
    println!("Input nullifier: 0x{}", hex::encode(&nf[..8]));

    // Change output (if any)
    let change_value = value - withdraw_amount;
    let (n_out, cm_change, change_rho, change_pk_spend, change_pk_ivk) = if change_value > 0 {
        let change_rho: Hash32 = rand::thread_rng().gen();
        // Keep change owned by the same spend key.
        let change_pk_spend: Hash32 = pk_spend_owner;
        let change_pk_ivk: Hash32 = pk_ivk_owner;
        let change_recipient: Hash32 =
            recipient_from_pk_v2(&domain, &change_pk_spend, &change_pk_ivk);
        let sender_id_out = in_recipient;
        let cm_change = note_commitment(
            &domain,
            u64::try_from(change_value).context("Change value too large")?,
            &change_rho,
            &change_recipient,
            &sender_id_out,
        );
        (
            1usize,
            Some(cm_change),
            Some(change_rho),
            Some(change_pk_spend),
            Some(change_pk_ivk),
        )
    } else {
        (0usize, None, None, None, None)
    };

    let public_output = SpendPublic {
        anchor_root: anchor,
        // Filled after fetching deny-map openings (defaults to all-allowed when NODE_API_URL is unset).
        blacklist_root: midnight_privacy::default_blacklist_root(),
        nullifier: nf,
        withdraw_amount,
        output_commitments: cm_change.into_iter().collect(),
        view_attestations: None,
    };

    let program_path = std::env::var("LIGERO_PROGRAM_PATH")?;
    let packing: u32 = std::env::var("LIGERO_PACKING")
        .unwrap_or_else(|_| "8192".to_string())
        .parse()
        .context("Invalid LIGERO_PACKING")?;

    // note_spend_guest v2 ABI builder (includes inv_enforce + deny-map section).
    let input = note_spend_guest_v2::SpendInputV2 {
        value: value_u64,
        rho,
        sender_id: in_sender_id,
        pos: position,
        siblings: siblings.clone(),
        nullifier: nf,
    };

    let mut outputs: Vec<note_spend_guest_v2::SpendOutputV2> = Vec::new();
    if n_out == 1 {
        outputs.push(note_spend_guest_v2::SpendOutputV2 {
            value: u64::try_from(change_value).context("Change value too large")?,
            rho: change_rho.expect("change_rho missing for change output"),
            pk_spend: change_pk_spend.expect("change_pk_spend missing for change output"),
            pk_ivk: change_pk_ivk.expect("change_pk_ivk missing for change output"),
            cm: cm_change.expect("cm_change missing for change output"),
        });
    }

    let sender_addr = PrivacyAddress::from_keys(&pk_spend_owner, &pk_ivk_owner);

    let withdraw_amount_u64 =
        u64::try_from(withdraw_amount).context("WITHDRAW_AMOUNT too large for u64")?;

    // Deny-map root + openings:
    // - always: sender_id
    // - transfer only (withdraw_amount == 0): pay recipient (output 0)
    // Change outputs are enforced to be self in-circuit and are not checked separately.
    let addr_list = if withdraw_amount_u64 == 0 {
        vec![sender_addr, sender_addr]
    } else {
        vec![sender_addr]
    };
    let node_url = std::env::var("NODE_API_URL").ok();
    let (blacklist_root, deny_openings) =
        note_spend_guest_v2::deny_map_openings_or_default(node_url.as_deref(), &addr_list)?;

    let withdraw_to: Hash32 = if withdraw_amount_u64 == 0 {
        [0u8; 32]
    } else {
        note_spend_guest_v2::withdraw_to_from_address_bytes(to_addr.as_ref())?
    };

    let (args, private_indices) = note_spend_guest_v2::build_note_spend_args_v2(
        domain,
        spend_sk,
        pk_ivk_owner,
        tree_depth,
        anchor,
        &[input],
        withdraw_amount_u64,
        withdraw_to,
        &outputs,
        blacklist_root,
        &deny_openings,
    )?;

    let mut host = <Ligero as Zkvm>::Host::from_args(&program_path)
        .with_packing(packing)
        .with_private_indices(private_indices);
    note_spend_guest_v2::add_args_to_host(&mut host, &args)?;

    let mut public_output = public_output;
    public_output.blacklist_root = blacklist_root;
    host.set_public_output(&public_output)?;

    println!("Generating proof...");
    let proof_bytes = host
        .run(true)
        .context("Ligero prover did not produce a valid proof")?;
    println!("✓ Proof generated: {} bytes", proof_bytes.len());

    let key_data: PrivateKeyAndAddress<DemoRollupSpec> =
        serde_json::from_str(&fs::read_to_string(std::env::var("PRIVATE_KEY_FILE")?)?)?;

    let proof_safe = proof_bytes
        .try_into()
        .map_err(|_| anyhow::anyhow!("Proof too large"))?;

    let msg = RuntimeCall::<DemoRollupSpec>::MidnightPrivacy(CallMessage::Withdraw {
        proof: proof_safe,
        anchor_root: anchor,
        nullifier: nf,
        withdraw_amount,
        to: to_addr,
        view_ciphertexts: None,
        gas: None,
    });

    let tx: Transaction<Runtime<DemoRollupSpec>, DemoRollupSpec> =
        default_test_signed_transaction(&key_data.private_key, &msg, nonce, &CHAIN_HASH);

    let tx_bytes = borsh::to_vec(&tx)?;
    fs::write("midnight_withdraw_tx.bin", &tx_bytes)?;

    let tx_base64 = base64::Engine::encode(&base64::engine::general_purpose::STANDARD, &tx_bytes);
    let tx_json = serde_json::json!({"body": tx_base64});

    fs::write(
        "midnight_withdraw_tx.json",
        serde_json::to_string_pretty(&tx_json)?,
    )?;

    println!("✓ Transaction ready: midnight_withdraw_tx.json");
    Ok(())
}
