use anyhow::Result;
use borsh;
use demo_stf::runtime::{Runtime, RuntimeCall};
use hex;
use midnight_privacy::{note_commitment, nullifier, CallMessage, Hash32, MerkleTree, SpendPublic};
use rand::Rng;
use serde_json;
use sov_cli::wallet_state::PrivateKeyAndAddress;
use sov_ligero_adapter::Ligero;
use sov_modules_api::execution_mode::Native;
use sov_modules_api::transaction::Transaction;
use sov_modules_rollup_blueprint::RollupBlueprint;
use sov_rollup_interface::zk::{Zkvm, ZkvmHost};
use sov_rollup_ligero::MockDemoRollup;
use sov_test_utils::default_test_signed_transaction;
use std::fs;
use serde::Deserialize;

type DemoRollupSpec = <MockDemoRollup<Native> as RollupBlueprint<Native>>::Spec;

mod demo_generated {
    include!("../../../examples/rollup-ligero/autogenerated.rs");
}

const CHAIN_HASH: [u8; 32] = demo_generated::CHAIN_HASH;

#[derive(Deserialize)]
struct NotesResponse {
    notes: Vec<NoteEntry>,
    current_root: Option<Vec<u8>>,
}

#[derive(Deserialize)]
struct NoteEntry {
    position: u64,
    commitment: Vec<u8>,
}

fn load_notes_from_source() -> Option<NotesResponse> {
    if let Ok(path) = std::env::var("NOTES_FILE") {
        let data = fs::read_to_string(path).ok()?;
        return serde_json::from_str(&data).ok();
    }

    if let Ok(node_url) = std::env::var("NODE_API_URL") {
        let url = format!("{}/modules/midnight-privacy/notes?limit=200&reverse=true", node_url);
        if let Ok(resp) = reqwest::blocking::get(url) {
            return resp.json::<NotesResponse>().ok();
        }
    }
    None
}

fn main() -> Result<()> {
    let domain: Hash32 = hex::decode(std::env::var("OUT1_DOMAIN")?)?
        .try_into()
        .map_err(|_| anyhow::anyhow!("Invalid domain"))?;
    let value: u128 = std::env::var("OUT1_VALUE")?.parse()?;
    let rho: Hash32 = hex::decode(std::env::var("OUT1_RHO")?)?
        .try_into()
        .map_err(|_| anyhow::anyhow!("Invalid rho"))?;
    let recipient_hash: Hash32 = hex::decode(std::env::var("OUT1_RECIPIENT")?)?
        .try_into()
        .map_err(|_| anyhow::anyhow!("Invalid recipient"))?;
    let nf_key: Hash32 = hex::decode(std::env::var("OUT1_NF_KEY")?)?
        .try_into()
        .map_err(|_| anyhow::anyhow!("Invalid nf_key"))?;
    let withdraw_amount: u128 = std::env::var("WITHDRAW_AMOUNT")?.parse()?;
    let position: u64 = std::env::var("OUT1_POSITION")?.parse()?;
    let nonce: u64 = std::env::var("NONCE")?.parse()?;
    let recipient_addr: String = std::env::var("RECIPIENT")?;

    let anchor_bytes: Vec<u8> = serde_json::from_str(&std::env::var("TRANSFER_ROOT")?)?;
    let mut anchor: Hash32 = anchor_bytes
        .try_into()
        .map_err(|_| anyhow::anyhow!("Invalid anchor"))?;

    let cm = note_commitment(&domain, value, &rho, &recipient_hash);
    let nf = nullifier(&domain, &nf_key, &rho);

    // Build tree from on-chain notes when available; otherwise fall back to single-leaf tree.
    let tree_depth: u8 = 16;
    let mut tree = MerkleTree::new(tree_depth);
    if let Some(notes_resp) = load_notes_from_source() {
        for note in notes_resp.notes {
            if note.position >= (1u64 << tree_depth) {
                continue;
            }
            if let Ok(commitment) = note.commitment.clone().try_into() {
                tree.set_leaf(note.position as usize, commitment);
            }
        }
        // Ensure our note is present (in case not returned due to limit/filter)
        tree.set_leaf(position as usize, cm);

        let computed_root: Hash32 = tree
            .root()
            .try_into()
            .map_err(|_| anyhow::anyhow!("Computed root has invalid length"))?;
        if computed_root != anchor {
            println!(
                "ℹ️  Recomputed anchor from notes differs from provided anchor; using computed root"
            );
            anchor = computed_root;
        }
    } else {
        tree.set_leaf(position as usize, cm);
    }
    let siblings = tree.open(position as usize);

    println!(
        "Withdraw: {} → {} (transparent) + {} (change)",
        value,
        withdraw_amount,
        value - withdraw_amount
    );
    println!("Input nullifier: 0x{}", hex::encode(&nf[..8]));

    // Create change note
    let change_value = value - withdraw_amount;
    let change_rho: Hash32 = rand::thread_rng().gen();
    let change_recipient: Hash32 = rand::thread_rng().gen();
    let cm_change = note_commitment(&domain, change_value, &change_rho, &change_recipient);

    let public_output = SpendPublic {
        anchor_root: anchor,
        nullifier: nf,
        withdraw_amount,
        output_commitments: vec![cm_change],
        view_attestations: None,
    };

    let program_path = std::env::var("LIGERO_PROGRAM_PATH")?;
    let packing: u32 = std::env::var("LIGERO_PACKING")?.parse()?;

    let mut private_indices = vec![2, 3, 4, 5, 6];
    for i in 0..tree_depth as usize {
        private_indices.push(8 + i);
    }
    let base = 12 + tree_depth as usize;
    private_indices.extend(&[base, base + 1, base + 2]);

    let mut host = <Ligero as Zkvm>::Host::from_args(&program_path)
        .with_packing(packing)
        .with_private_indices(private_indices);

    // Typed binary ABI for zkVM performance
    host.add_hex_arg(hex::encode(domain));
    host.add_u64_arg(value);
    host.add_hex_arg(hex::encode(rho));
    host.add_hex_arg(hex::encode(recipient_hash));
    host.add_hex_arg(hex::encode(nf_key));
    host.add_u64_arg(position);
    host.add_u64_arg(tree_depth as u64);

    for sibling in &siblings {
        host.add_hex_arg(hex::encode(sibling));
    }

    host.add_hex_arg(hex::encode(anchor));
    host.add_hex_arg(hex::encode(nf));
    host.add_u64_arg(withdraw_amount);
    host.add_u64_arg(1); // n_out = 1 (change)

    // Change output
    host.add_u64_arg(change_value);
    host.add_hex_arg(hex::encode(change_rho));
    host.add_hex_arg(hex::encode(change_recipient));
    host.add_hex_arg(hex::encode(cm_change));

    host.set_public_output(&public_output)?;

    println!("Generating proof...");
    let proof_bytes = host.run(true)?;
    println!("✓ Proof generated: {} bytes", proof_bytes.len());

    let key_data: PrivateKeyAndAddress<DemoRollupSpec> =
        serde_json::from_str(&fs::read_to_string(std::env::var("PRIVATE_KEY_FILE")?)?)?;

    let proof_safe = proof_bytes
        .try_into()
        .map_err(|_| anyhow::anyhow!("Proof too large"))?;

    let recipient_parsed = recipient_addr
        .parse()
        .map_err(|e| anyhow::anyhow!("Invalid recipient address: {}", e))?;

    let msg = RuntimeCall::<DemoRollupSpec>::MidnightPrivacy(CallMessage::Withdraw {
        proof: proof_safe,
        anchor_root: anchor,
        nullifier: nf,
        withdraw_amount,
        to: recipient_parsed,
        view_ciphertexts: None,
        gas: None,
    });

    let tx: Transaction<Runtime<DemoRollupSpec>, DemoRollupSpec> =
        default_test_signed_transaction(&key_data.private_key, &msg, nonce, &CHAIN_HASH);

    let tx_bytes = borsh::to_vec(&tx)?;
    fs::write("midnight_withdraw_tx.bin", &tx_bytes)?;

    let tx_base64 = base64::Engine::encode(&base64::engine::general_purpose::STANDARD, &tx_bytes);
    let tx_json = serde_json::json!({"body": tx_base64});

    fs::write(
        "midnight_withdraw_tx.json",
        serde_json::to_string_pretty(&tx_json)?,
    )?;

    println!("✓ Transaction ready: midnight_withdraw_tx.json");
    Ok(())
}
