[package]
name = "mcp-external"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
homepage.workspace = true
publish.workspace = true
repository.workspace = true

[dependencies]
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "signal"] }
rmcp = { version = "0.10", features = [
    "server",
    "transport-streamable-http-server",
] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
anyhow = { workspace = true }
dotenvy = "0.15"
envy = "0.4"
url = { version = "2", features = ["serde"] }
axum = "0.8"
validator = { version = "0.18", features = ["derive"] }
hex = { workspace = true }
bincode.workspace = true
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
reqwest = { version = "0.12", features = ["json"] }
ligero-runner = { git = "https://github.com/dcSpark/ligero-prover.git", rev = "8c69805f001e6c15c967181d5524da8284c94844" }
uuid = { workspace = true, features = ["v5", "v4", "std"] }
sqlx = { version = "0.8.6", default-features = false, features = ["runtime-tokio-rustls", "macros", "sqlite"] }
tracing-appender = { workspace = true }

# Sovereign SDK dependencies for wallet integration
sov-cli = { workspace = true }
sov-modules-api = { workspace = true, features = ["native"] }
sov-bank = { workspace = true }
sov-node-client = { workspace = true }
sov-address = { workspace = true }
demo-stf = { workspace = true, features = ["native"] }
sov-mock-da = { workspace = true, features = ["native"] }
sov-ligero-adapter = { workspace = true }
sov-mock-zkvm = { workspace = true }
base64.workspace = true
borsh.workspace = true
sov-value-setter-zk.workspace = true
sov-modules-stf-blueprint.workspace = true
midnight-privacy = { workspace = true }
rand = { workspace = true }
sov-api-spec = { workspace = true }
ligetron = { git = "https://github.com/dcSpark/ligero-prover.git", rev = "8c69805f001e6c15c967181d5524da8284c94844" }

[dev-dependencies]
dirs = "6.0.0"
tokio = { workspace = true, features = ["macros"] }
tracing-test = { workspace = true }

[lints]
workspace = true
